<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form;
    $url_cencel =  $this->url(array('module'=>'sales','controller'=>'workplan','action'=>'index'));
?>						 
<title><?php echo $tr->translate("ADD_NEW_ITEM");?></title>
	<form class="form-horizontal" method="post" autocomplete="off">				
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i><?php echo $tr->translate("ADD_NEW_PRODUCT");?>
				</div>
				<div class="tools">
					<label><a href="<?php echo $url_cencel;?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i><?php echo $tr->translate("GO_BACK");?></button></a></label>
				</div>
			</div>
			<div class="portlet-body">
				<div class="tabbable-custom ">
					<div class="tab-content">
						<div class="tab-pane active" id="tab_5_1">
							<div class="portlet-body form">
								<div class="form-body">
									<div class="form-group">
										<label class="col-md-1 control-label"><?php echo $tr->translate("NAME");?></label>
										<div class="col-md-3">
											<?php echo $form->getElement('name');?>
										</div>
										<label class="col-md-1 control-label"><?php echo $tr->translate("PLAN");?></label>
										<div class="col-md-3">
											<?php echo $form->getElement('plan');?>
										</div>
										<label class="col-md-1 control-label"><?php echo $tr->translate("STATUS");?></label>
										<div class="col-md-3">
											<?php echo $form->getElement('status');?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-md-12 col-md-offset-4 col-md-8">
											<a href="<?php echo $this->baseUrl();?>/sales/plan/workplan"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
											<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
											<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
										</label>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
</form>	