
<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'index','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("PRODUCT_LIST");?></title>
	<div class="row">
		<div class="col-md-12">
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-globe"></i><?php echo $tr->translate("PRODUCT_LIST");?>
					</div>
					<div class="pull-right">
						<a href="<?php echo $url_new;?>" class="btn btn-sm red" style="line-height: 35px;">
							<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
						</a>
					</div>
				</div>
				<div class="portlet-body form">
				<form method="post" action="" autocomplete="off">
					<div class="form-body">
						<div class="form-group" style="padding-top: 6px;">
							<div class="col-md-2"><?php echo $formFilter->getElement('ad_search');?></div>
							<div class="col-md-2"><?php echo $formFilter->getElement('branch');?></div>
							<div class="col-md-2"><?php echo $formFilter->getElement('brand');?></div>
							<div class="col-md-2"><?php echo $formFilter->getElement('category');?></div>
							<div class="col-md-2"><?php echo $formFilter->getElement('model');?></div>
							<div class="col-md-2"><?php echo $formFilter->getElement('size');?></div>
						</div>
						<div class="form-group">
							<div class="col-md-2"><?php echo $formFilter->getElement('color');?></div>
							<div class="col-md-2"><?php echo $formFilter->getElement('status');?></div>
							<div class="col-md-2"><?php echo $formFilter->getElement('stock_type');?></div>
							<div class="col-md-2">
								<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
							</div>
							<div class="btn-group pull-right">
								 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
								   <?php echo $tr->translate("ACTIONS");?> <i class="fa fa-angle-down"></i>
								 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate("PRINT");?>
										</a>
									</li>
									<li>
										<a href="#"  onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</form>
		<div style=" min-height:28cm; margin:25 0 0 0; padding:0px 0.2cm">
		<div id="divPrint" style="width: 100%;">
			<style>
				.style{
					line-height: 20px;font-size: 9px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
				th{padding: 5px;}
				.hover:hover{background: #ccc;}
				.center{text-align:center;}
			@media print {
			  a[href]:after {
			    content: none !important;
			  	color:#000 !important;
			  }
			}
		</style>
						<table style="font-family: 'Khmer OS Content'; width:100%;">
							<tr>
						    	<td align="center">
						        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
						            	<tbody>
											<tr style="margin-bottom:10px;"> 
												<td width="20%" valign="top"></td>
												<td width="60%" valign="top" style="line-height:30px">
													<ul>
														<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
														<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
														<li style="text-align:center; font-size:20px; margin: 15px 0px 7px 0px; font-family:'Khmer OS Muol Light',serif,header-font; "><?php echo $tr->translate("RPT_PL");?></li>
													</ul>
												</td>
												<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
												</td>
											</tr> 
							            </tbody>
						            </table>
						        </td>
						    </tr>
						    <tr>
						    	<td class="table2excel" >
									<div class="contain_form" style="clear: both;">
										<?php echo $this->list; ?>
									</div>
								</td>
							</tr>
						</table>
		 			</div>
				</div>	
	   		</div>
		</div>
	</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	var printContents = document.getElementById('divPrint').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
}
</script>