<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_purchase;
	$url_submit = $this->url(array('module'=>'product','controller'=>'index','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'product','controller'=>'receive','action'=>'receivedlist'));
?>
<title><?php echo $tr->translate("RECEIVE_STOCK");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("RECEIVE_STOCK")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2">
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_NO");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('invoice_no');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"></label>
							<div class="col-md-4">
								<div class="input-icon right">
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_DATE");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('invoice_date');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2">
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("RECEIVE_INVOICE_FROM_STOCK_DATE");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('invoice_recieve_date');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("DN_NO");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="col-md-6">
									<?php echo $form->getElement('dn_no');?>
								</div>
								<div class="col-md-6">
									<label class="control-label col-md-10"><?php echo $tr->translate("MAKE_INVOICE");?> : <span class="required">
										</span>
									</label>
									<div class="col-md-2" style="margin-top: 10px;">
										<input <?php if($this->data[0]["is_invoice_controlling"]==1){echo"checked";}?> type="checkbox" name="is_invoice" id="is_invoice" value="1" onClick="isInoice();" />
									</div>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("RECIEVE_NO");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('recieve_no');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("DN_DATE");?> : <span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('dn_date');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("RECEIVE_DATE");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('date_recieve');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PLAN");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4" >
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("plan");?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("BRANCH");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("branch");?>
								</div>
							</div>
						</div>
						<div class="form-group" style="pointer-events: none;cursor: default;">
							<label class="control-label col-md-2"><?php echo $tr->translate("PURCHASE_NO");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("pu_code");?><?php echo $form->getElement("re_id");?>
									<input type="hidden" name="branch_id" id="branch_id" />
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("REQUEST_NO");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("re_code");?>
								</div>
							</div>
						</div>
						<div class="form-group" style="pointer-events: none;cursor: default;">
							<label class="control-label col-md-2"><?php echo $tr->translate("PURCHASE_DATE");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('date_order');?>
								</div>
							</div>	
							<label class="control-label col-md-2"><?php echo $tr->translate("REQUEST_DATE");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('re_date');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("VENDOR_NAME");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4"  style="pointer-events: none;cursor: default;">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("vendor");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?> : <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
						</div>
						<div class="form-group"></div>
								<div class="portlet-body" style="">
									<div class="col-md-12" style=" float:right;">
											<div class="form-group">
												<div class="col-md-12">
													<label class="control-label col-md-1">
														<?php echo $tr->translate("PLATE_NO");?>
													</label>
													<div class="col-md-1">
														<div class="input-icon right">
															<i class="fa"></i>
															<input type="text" name="plat_no" value="<?php echo $this->data[0]["plat_no"];?>" id="plat_no" onKeyup=" CalcualteScale(1,2);" class="form-control" />
														</div>
													</div>
													<label class="control-label col-md-2">
														<?php echo $tr->translate("SU_SCALE_REFER");?>
													</label>
													<div class="col-md-1">
														<div class="input-icon right">
															<i class="fa"></i>
															<input type="text" name="su_scale_refer" value="<?php echo $this->data[0]["su_scale_refer"];?>" id="su_scale_refer" onKeyup=" CalcualteScale(1,2);" class="form-control" />
														</div>
													</div>
													<label class="control-label col-md-2">
														<?php echo $tr->translate("SUPPLIER_SCALE");?>
													</label>
													<div class="col-md-1">
														<div class="input-icon right">
															<i class="fa"></i>
															<input type="text" name="supplier_scale" id="supplier_scale" value="<?php echo $this->data[0]["su_scale_qty"];?>" onKeyup=" CalcualteScale(1,1);" class="form-control" />
														</div>
													</div>
													<label class="control-label col-md-2">
														<?php echo $tr->translate("TOTAL_IN_M3");?>
													</label>
													<div class="col-md-1">
														<div class="input-icon right">
															<i class="fa"></i>
															<input type="text" name="supplier_scale_total" id="supplier_scale_total" readOnly="readOnly" value="<?php echo $this->data[0]["su_scale_in_m"];?>" class="form-control" />
														</div>
													</div>
													<label class="control-label col-md-1" style="padding:7px 0">
														<?php echo $tr->translate("CHOOSE");?>
													
															<input type="radio" onClick="setValue();" value="1" name="choose" id="choose" />
													</label>
												</div>
											</div>
										<div class="form-group">
											<div class="col-md-12">
												<label class="control-label col-md-1"><?php echo $tr->translate("NO_CONVERT");?></label>
												<div class="col-md-1" style="padding: 7px 0;">
													<div class="input-icon right">
														<i class="fa"></i>
														<input type="checkbox" name="unblock" id="unblock" onClick="unBlock()"/>
													</div>
												</div>
												<label class="control-label col-md-2">
													<?php echo $tr->translate("COM_SCALE_REFER");?>
												</label>
												<div class="col-md-1">
													<div class="input-icon right">
														<i class="fa"></i>
														<input type="text" name="com_scale_refer" value="<?php echo $this->data[0]["com_scale_refer"];?>" id="com_scale_refer" onKeyup=" CalcualteScale(1,2);" class="form-control" />
													</div>
												</div>
												<label class="control-label col-md-2">
													<?php echo $tr->translate("COMPANY_SCALE");?>
												</label>
												<div class="col-md-1">
													<div class="input-icon right">
														<i class="fa"></i>
														<input type="text" name="company_scale" value="<?php echo $this->data[0]["com_scale_qty"];?>" id="company_scale" onKeyup=" CalcualteScale(1,2);" class="form-control" />
													</div>
												</div>
												<label class="control-label col-md-2">
													<?php echo $tr->translate("TOTAL_IN_M3");?>
												</label>
												<div class="col-md-1">
													<div class="input-icon right">
														<i class="fa"></i>
														<input type="text" name="company_scale_total" id="company_scale_total"​ readOnly="readOnly" value="<?php echo $this->data[0]["com_scale_in_m"];?>" class="form-control" />
													</div>
												</div>
												
												<label class="control-label col-md-1" style="padding: 7px 0;">
													<?php echo $tr->translate("CHOOSE");?>
												
													<span>
														<input type="radio" onClick="setValue();" value="2" checked name="choose" id="choose" />
													</span>
												</label>
											</div>
										</div>
									</div>
								</div>
								<div style="clear:both;"></div>
								<hr />
								<div class="portlet-body">
									<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
										<tr height="33px">
											<th><?php echo $tr->translate("NUM");?></th>
											<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_CODE");?></th>
											<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
											<th style="white-space:nowrap;"><?php echo $tr->translate("MEASURE");?></th>
											<th><?php echo $tr->translate("QTY_ORDER");?></th>
											<th><?php echo $tr->translate("REMEAN_QTY");?></th>
											<th><?php echo $tr->translate("QTY_RECIEVE");?></th>
											<th><?php echo $tr->translate("REMARK");?></th>
										</tr>
									 </table>
								 <input type="hidden" id="identity" name="identity" />
							</div>
							<div class="form-group">
								<?php echo $form->getElement("payment_name");?>
								<?php echo $form->getElement("vat");?>
								<?php echo $form->getElement("totalAmoun");?>
								<?php echo $form->getElement("totalAmoun_after");?>
								<?php echo $form->getElement("currency");?>
								<?php echo $form->getElement("dis_value");?>
								<?php echo $form->getElement("total_tax");?>
								<?php echo $form->getElement("all_total");?>
								<?php echo $form->getElement("all_total_after");?>
								<?php echo $form->getElement("paid");?>
								<?php echo $form->getElement("global_disc");?>
								<?php echo $form->getElement("remain");?>
								<?php echo $form->getElement("remain_after");?>
						</div>
						<div class="form-group">
							<div  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/product/receive/receivedlist/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function() {
	initList();
	$('#pu_code').attr("readOnly",true); 
	$('#vendor').attr("readOnly",true); 
	isInoice();
});
function CalcualteScale(index,type){
	measure_convertor = $("#measure_convertor_"+index).val();
	sign = $("#sign_"+index).val();
	if(type==1){
		scale = $("#supplier_scale").val();
		conveted = $("#supplier_scale_total");
	}else{
		scale = $("#company_scale").val();
		conveted = $("#company_scale_total");
	}
	total = parseFloat(scale)/parseFloat(measure_convertor);
	conveted.val(total.toFixed(2));
	setValue();
}
function setValue(){
	 val = $("input:radio[name=choose]:checked").val()
	if(val==1){
		conveted =  parseFloat($("#supplier_scale_total").val());
	}else{
		conveted = parseFloat($("#company_scale_total").val());
	}
	$("#qty_recieve_1").val(conveted);
	calculatePrice(1);
}

function unBlock(){
	if($("#unblock").is(':checked')){
		if(is_convertorn==1){
			$("#qty_recieve_1").attr("readOnly",false);
		}
	}else{
		if(is_convertorn==1){
			$("#qty_recieve_1").attr("readOnly",true);
		}
	}
}
index=0;
function isInoice(){
	is_invoice = $("#is_invoice");
	if($("#is_invoice").is(':checked')){
		$('#invoice_no').attr("required",true);
		$('#invoice_no').attr("readOnly",false);
		
		$('#invoice_date').attr("required",true);
		$('#invoice_date').attr("readOnly",false);
		
		$('#invoice_recieve_date').attr("required",true);
		$('#invoice_recieve_date').attr("readOnly",false);
		
	}else{
		$('#invoice_no').attr("required",false);
		$('#invoice_no').attr("readOnly",true);
		$('#invoice_date').attr("required",false);
		$('#invoice_date').attr("readOnly",true);
		
		$('#invoice_recieve_date').attr("required",false);
		$('#invoice_recieve_date').attr("readOnly",true);
	}
}
function initList() {
	index5=0;
	var template;
	var option5 = '<?php echo $this->items;?>';
	<?php if(!empty($this->data)) {
		foreach($this->data AS $i=>$r){?>
	is_convertorn = '<?php echo $r["is_convertor"];?>';
	if(is_convertorn==1){
		readOnly = "readOnly='readOnly'";
	}else{
		readOnly="";
	}
	index5++; 
	index=index+1;
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	    item_name='<?php echo preg_replace("/'/", "\&#39;", $r['item_name']);?>';
		template+='<td  width="1%">'+index5+'</td>';
		template+='<td width="15%"><?php echo $r['item_code'];?><input type="hidden" name="item_code_'+index5+'" id="item_code_'+index5+'" /></td>';
		template+='<td width="30%">'+item_name+'<input type="hidden" name="item_id_'+index5+'" id="item_id_'+index5+'" value="<?php echo $r['pro_id'];?>" /></td>';
		template+='<td width="7%"><?php echo $r['measure'];?><input type="hidden" name="is_convertor_'+index5+'" id="is_convertor_'+index5+'" value="'+is_convertorn+'" /></td>';
		template+='<td ><input type="text" class="form-control" required="1" readOnly="readOnly" value="<?php echo $r['origin_qty_order'];?>" id="origin_qty_order_'+index5+'" name="origin_qty_order_'+index5+'" /></td>';
		template+='<td ><input type="text" class="form-control" required="1" readOnly="readOnly" value="<?php echo $r['qty_order'];?>" id="qty_order_'+index5+'" name="qty_order_'+index5+'" /><input type="hidden" class="form-control" required="1" readOnly="readOnly" value="<?php echo $r['qty_receive'];?>" id="old_qty_order_'+index5+'" name="old_qty_order_'+index5+'" /></td>';
		template+='<td><input type="text" '+readOnly+' class="validate[required,custom[number]] input form-control" onkeypress="return isNumberKey(event)" required="required" onKeyup="calculatePrice('+index5+')" value="<?php echo $r['qty_receive'];?>" id="qty_recieve_'+index5+'" name="qty_recieve_'+index5+'" /><input type="hidden" name="measure_convertor_'+index5+'" id="measure_convertor_'+index5+'" value="<?php echo $r["convertor_measure"]?>" /><input type="hidden" name="sign_'+index5+'" id="sign_'+index5+'" value="<?php echo $r["sign"]?>" /></td>';
		template+='<td ><input type="text" class="form-control" id="remark_'+index5+'" name="remark_'+index5+'" /> <input type="hidden" name="price_'+index5+'" id="price_'+index5+'" value="<?php echo $r['price'];?>" /> <input type="hidden" name="total_after_'+index5+'" id="total_after_'+index5+'" value="<?php echo $r['sub_total_after'];?>" /><input type="hidden" name="total_'+index5+'" id="total_'+index5+'" value="<?php echo $r['sub_total'];?>" /><input type="hidden" value="<?php echo $r['disc_value'];?>" id="dis_value'+index5+'" name="dis_value'+index5+'" class="form-control" /><input type="hidden" name="sub_total_receive_'+index5+'" id="sub_total_receive_'+index5+'" /> </td>';
		template+="</tr>";
	$('#table_order').append(template);

	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	
	$("#row_order_0").remove();
	calculatePrice(index5);
		<?php } }?>
}
function netTotal() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = ($('#dis_value').val());
	if(discountValue==''){$('#dis_value').val(0);discountValue=0;}
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun").val();
				totalpayment = alltotal - discountValue;
				$('#all_total').val(totalpayment);
		}
		doRemain();
	}
}
function doRemain() {
	var all_total = parseFloat($('#all_total').val());
	var paid = $('#paid').val();
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		 $('#remain').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain').val(remain.toFixed(2));
	}
}
function calculatePrice(index) {
	var qty = parseFloat($('#qty_recieve_'+index).val());
	qty_after = parseFloat($('#qty_order_'+index).val());
	if(qty>qty_after){
		alert("You can Receive Only Equal Remean QTY");
	}
	var price = parseFloat($('#price_'+index).val());
	var total = price * parseFloat($('#qty_recieve_'+index).val());
	var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
				
			}else{
				after_discount = total - discount;
			}
			$('#total_after_'+index).val(after_discount.toFixed(2));
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total_after_'+index).val(parseFloat(after_discount).toFixed(2));
		}
		netTotal();
	}
}
function calculatePrice(index) {
	var qty = parseFloat($('#qty_recieve_'+index).val());
	var price = $('#price_'+index).val();
	var total = price * qty;
	var ds = $('#dis_value'+index).val();
	qty_after = parseFloat($('#qty_order_'+index).val());
	if(qty>qty_after){
		alert("You can Receive Only Equal Remean QTY");
	}
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total - discount;
			}else{
				after_discount = total - discount;
			}
			$('#total_after_'+index).val(after_discount.toFixed(2));
		}else{
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total - discount;
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total_after_'+index).val(parseFloat(after_discount).toFixed(2));
		}
		netTotal();
	}
}
function netTotal() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	var all_total_amount = 0;
	var all_total =0;
	var total_tax =0;
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total_after_'+rowIDArray[n]).val());
		all_total_amount += Number($('#total_'+rowIDArray[n]).val());
		all_total += Number($('#total_'+rowIDArray[n]).val());
	}
	total_tax = all_total_amount*(parseFloat($('#vat').val())/100);
	$('#totalAmoun').val(all_total_amount);
	$('#all_total').val(all_total+total_tax);
	$('#totalAmoun_after').val(netTotal.toFixed(2));
	$('#all_total_after').val(netTotal.toFixed(2));
	$('#remain').val(netTotal.toFixed(2));
	 doRemain();
}
function doRemain() {
	var all_total = parseFloat($('#all_total_after').val());
	var paid = $('#paid').val();
	if(paid>all_total){
		alert("Paid Value can not biger then total amount !");
		 $('#remain_after').val(all_total.toFixed(2));
   }else{
	   remain = all_total-paid;
	   $('#remain_after').val(remain.toFixed(2));
	}
}

<?php $url_code =  $this->url(array('module'=>'purchase','controller'=>'receive','action'=>'get-receive-code')); ?>
function getReceiveCode(){
	branch_id = $('#branch').val();
	$.ajax({
		url:"<?php echo $url_code;?>",
		type:"post",
		data:{'branch_id':branch_id},
		success: function(data){
			rs = $.parseJSON(data);	
			$('#request_no').val(rs);
		},
		error:function(e){
		}
	});
}
</script>	