<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  $rpt_purchase=$this->url(array('module'=>'report','controller'=>'report','action'=>'rpt-purchase'), null, true);
  $rpt_purcahsedetail=$this->url(array('module'=>'report','controller'=>'report','action'=>'rpt-purchaseitem'), null, true);
  $rpt_sale=$this->url(array('module'=>'report','controller'=>'report','action'=>'rpt-sales'), null, true);
  $rpt_saledetail=$this->url(array('module'=>'report','controller'=>'report','action'=>'rpt-saleitem'), null, true);
  $rpt_customer=$this->url(array('module'=>'report','controller'=>'report','action'=>'rpt-customer'), null, true);
  $rpt_saleperson=$this->url(array('module'=>'report','controller'=>'report','action'=>'rpt-saleperson'), null, true);
  
  ?>
<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat blue-madison">
						<a class="more" href="<?php echo $rpt_purchase;?>">
						<div class="visual">
							<i class="fa fa-comments"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 Purchase Report
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_purchase;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat red-intense">
						<a class="more" href="<?php echo $rpt_purcahsedetail;?>">
						<div class="visual">
							<i class="fa fa-bar-chart-o"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 Purchase Product Detail
							</div>
						</div>
						</a>
						<a class="more" href="<?php echo $rpt_purcahsedetail;?>">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat green-haze">
						<a class="more" href="<?php echo $this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-quotationissue'), null, true);?>">
						<div class="visual">
							<i class="fa fa-shopping-cart"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 Sale Quotation
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat green-haze">
						<a class="more" href="<?php echo $rpt_sale;?>">
						<div class="visual">
							<i class="fa fa-shopping-cart"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 Sale Report
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_saledetail;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 Sale Porudct Detail
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat green-haze">
						<a class="more" href="<?php echo $this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-delivery'), null, true);;?>">
						<div class="visual">
							<i class="fa fa-shopping-cart"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 Invoice/Delivery
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_customer;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 Customer Report
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_saleperson;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 Sale Person Report
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_saledetail;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 suppliyer Report
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat purple-plum">
						<a class="more" href="<?php echo $rpt_saledetail;?>">
						<div class="visual">
							<i class="fa fa-globe"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 Customer Balance Report
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						<?php echo $tr->translate("VIEW_MORE");?><i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
			</div>