<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$brach_name =  $this->branch;
	$formFilter = $this->formFilter;
?>
<title>Closing Stock</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
            <div class="portlet-body form frmfilter">
				<form method="post" style="border-bottom: 1px solid #ccc;" >
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('ad_search');?>
							</label>
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('branch');?>
							</label>
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('category');?>
							</label>
							<label class="control-label col-md-3  pull-right">
								<button type="submit" class="btn btn-primary col-md-12"><?php echo $tr->translate("SEARCH");?></button>
							</label>
						</div>
					</div>
					<div style="clear: both;"></div>
				</form>  
	<div style="clear: both;"></div>
	<div style=" min-height:28cm; margin:25 0 0 0; padding:0px 0.2cm">
		<div id="divPrint" style="width: 100%;">
			<style>
				.style{
					line-height: 20px;font-size: 9px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
				th{padding: 5px;}
				.hover:hover{background: #ccc;}
			</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
							<tr style="margin-bottom:10px;"> 
								<td width="20%" valign="top"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;">Closing Ending Balance Stock</li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;"></td>
				            </tr>
			            </table>
			        </td>
			    </tr>
			    <tr>
			    	<td class="table2excel" >
			            <form id="frmProduct" name="frmProduct" id="a" class="form-horizontal" action="<?php echo $this->url(array('module'=>'report','controller'=>'product','action'=>'submitclosing')); ?>" enctype="multipart/form-data" method="post">
				            <table border="1" class="collape tablesorter" style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
				                <tbody >
									<tr style="background:#ccc ; font-size:13px !important;">
										<th class="tdheader"><?php echo $tr->translate("NUM");?></th>
										<th class="tdheader"><?php echo $tr->translate("BRANCH");?></th>
										<th class="tdheader"><?php echo $tr->translate("ITEM_CODE");?></th>
										<th class="tdheader"><?php echo $tr->translate("ITEM_NAME");?></th>
										<th class="tdheader"><?php echo $tr->translate("BARCODE");?></th>
										<th class="tdheader"><?php echo $tr->translate("CATEGORY");?></th>
										<th class="tdheader"><?php echo $tr->translate("MEASURE");?></th>
										<th class="tdheader"><?php echo $tr->translate("QTY");?></th>
										<th><?php echo $tr->translate("ចំនួនជាក់ស្តែង");?></th>
									</tr>
					                <?php 
					                $num=1; 
					                if(!empty($this->product))foreach ($this->product AS $index => $row){
					                	if($index==0){
					                		$str=$index+1;
					                	}else{
					                		$str.=",".($index+1);
					                	}
					                ?>
										<tr class="odd gradeX hover" id="item_<?php echo $index; ?>">
											<td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1; ?></td>
											<td style="white-space: nowrap;" class="center">&nbsp;<?php //echo $row["branch"]?></td>
											<td style="white-space: nowrap;">&nbsp;<?php echo $row["item_code"]?></td>
											<td style="white-space: nowrap;">&nbsp;<?php echo $row["item_name"]?></td>
											<td style="white-space: nowrap;">&nbsp;<?php echo $row["barcode"]?></td>
											<td><?php echo $row["cat"]?></td>
											<td style="white-space: nowrap;"><?php echo $row["measure"]?></td>
											<td style="white-space: nowrap;"><?php echo !empty($row["qty"])?$row["qty"]:0?></td>
											<td style="white-space: nowrap;">
												<input name="pro_id<?php echo $index+1;?>" value="<?php echo $row["id"]?>" />
												<input required="true" name="qty_<?php echo $index+1;?>" value="<?php echo $row["qty"]?>" />
											</td>
										</tr>
									<?php }?> 
				                </tbody>
			                	<tr>
			                		<td style="text-align: center;" colspan="9">
			                			<br />
			                				<input class="form-control date-picker" type="text" name="from_date" id="from_date" value="<?php echo date('d-m-Y'); ?>" />
			                				<input class="form-control date-picker" type="text" name="to_date" id="to_date" value="<?php echo date('d-m-Y'); ?>" />
			                				<input type="text" name="identity" id="identity" value="<?php echo $str;?>" />
			                				<input type="button" class="btn btn-primary" onclick="submitClosing();"  /> 
			               					<button type="submit" class="btn btn-primary" value="" ><i class="fa fa-save"></i>&nbsp;Submit</button>
			               				<br />
			               			</td>
			                	</tr>
				           </table>
				          </form>
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<script>
<?php $url_submit =  $this->url(array('module'=>'report','controller'=>'product','action'=>'submitclosing')); ?>
function submitClosing(){
	 var form = $("#frmProduct");
	  var formdata = form.serialize();
	  
	//alert($('#frmProduct').serialize());
	$.ajax({
		url:"<?php echo $url_submit;?>",
		type:"post",			
		data: formdata,
		success: function(data){
			//value = $.parseJSON(data);
			alert(data);
		},
		error:function(request, error){
			console.log(arguments);
	        alert(" Can't do because: "+error);
		}
	});
}
function doPrint(){
	var printContents = document.getElementById('divPrint').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
}
</script>