<?php 
	$url_new = $this->url(array('module'=>'model','controller'=>'index','action'=>'add',));
	$url_edit = $this->url(array('module'=>'model','controller'=>'index','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'model','controller'=>'index','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	
	$rs = $this->resulr;
?>
<title><?php echo $tr->translate("MODEL_LIST");?></title>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("MENU_MODEL_ADVANCE_INDEX");?>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="form-group">
								<label class="col-md-1 control-label"><?php echo $tr->translate("SEARCH");?></label>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('name');?>
								</div>
												
								<label class="col-md-1 control-label"><?php echo $tr->translate("PARENT");?></label>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('parent');?>
								</div>
								<label class="col-md-1 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('status');?>
								</div>
							</div>
						<div class="form-group">
						<div class="row">
                            <div class="col-md-offset-3 col-md-12">
                                <button type="submit" class="btn green"><?php echo $tr->translate("SEARCH");?></button>
                                <button type="button" class="btn default"><?php echo $tr->translate("CANCEL");?></button>
                            </div>
                        </div>
					</div>
				</div>
			</form>
			
		</div>
		
		<!-- Result List -->
					<!-- BEGIN EXAMPLE TABLE PORTLET-->
						
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="row">
									<div class="col-md-6">
										<div class="btn-group">
											<a href="<?php echo $url_new;?>"><button id="sample_editable_1_new" class="btn green">
											Add New <i class="fa fa-plus"></i>
											</button></a>
										</div>
									</div>
									<div class="col-md-6">
										<div class="btn-group pull-right">
											<button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="fa fa-angle-down"></i>
											</button>
											<ul class="dropdown-menu pull-right">
												<li>
													<a href="javascript:;">
													Print </a>
												</li>
												<li>
													<a href="javascript:;">
													Save as PDF </a>
												</li>
												<li>
													<a href="javascript:;">
													Export to Excel </a>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<table class="table table-striped table-bordered table-hover" id="sample_1">
							<thead>
								<tr>
									<th class="table-checkbox">
										<input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes"/>
									</th>
									<th><?php echo $tr->translate("MODEL_NAME");?></th>
									<th><?php echo $tr->translate("REMRK");?></th>
									<th><?php echo $tr->translate("STATUS");?></th>
									<th><?php echo $tr->translate("ACTION");?></th>
								</tr>
							</thead>
							<tbody>
								<?php if(!empty($rs)){ foreach ($rs as $key => $row){?>
								<tr class="odd gradeX">
									<td><input type="checkbox" class="checkboxes" value="<?php echo $row["id"]?>"/></td>
									<td><?php echo $row["name"]?></td>
									<td class="center"><?php echo $row["remark"]?></td>
									<td>
										<?php if($row["status"] == 1){?>
										<span class="label label-sm label-success"><?php echo $tr->translate("ACTIVE");?> </span>
										<?php }else{?>
										<span class="label label-sm label-danger"><?php echo $tr->translate("DEACTIVE");?> </span>
										<?php }?>
									</td>
									
									<td>
										<a href="<?php echo $url_edit;?>/id/<?php echo $row["id"]?>"><button type="button" class="btn btn-primary"><?php echo $tr->translate("EDIT");?></button></a>
										<a href="<?php echo $url_delete;?>/id/<?php echo $row["id"]?>"><button type="button" class="btn btn-danger"><?php echo $tr->translate("DELETE");?></button></a>
									</td>
								</tr>
								<?php }}?>
							</tbody>
							</table>
						</div>
					<!-- END EXAMPLE TABLE PORTLET-->
			<!-- End Result list -->
	</div>
</div>