<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$db = new Purchase_Model_DbTable_DbPriceCompare();
$total=0;
$vat=0;
?>
<title><?php echo $tr->translate("PRINT_COMPARE_PRICE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PRINT_COMPARE_PRICE");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<!--<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>-->
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%; margin-top:15px;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 0px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	   .center{text-align:center;}
		.backgroundcc{background:#ccc !important;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
							<tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:18px; margin-top:25px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("PRICE_COMPARE_LIST");?></li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
									<table width="100%" style="font-size: 12px; !important">
										<!--<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("NUMBER_REQUEST");?> </td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['number_request'];?></td>
										</tr>
										<tr>
											<td style="text-align: left; white-space:nowrap;"><?php echo $tr->translate("PLAN");?> </td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['plan'];?></td>
										</tr>
										<tr>
											<td style="text-align: left;white-space:nowrap;"><?php echo $tr->translate("DATE_REQUEST_WORK_SPACE");?> </td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d/m/Y",strtotime($this->product[0]['date_from_work_space']));?></td>
										</tr>-->
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("BRANCH_NAME");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['branch'];?></td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("COMPARE_PRICE_CODE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['c_code'];?> </td>
										</tr>
										<tr>
											<td style="text-align: right;white-space:nowrap;"><?php echo $tr->translate("COMPARE_DATE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d-M-Y",strtotime($this->product[0]['com_date']));?></td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("REQUEST_NO");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo $this->product[0]['re_code'];?></td>
										</tr>
										<tr>
											<td style="text-align: right;white-space:nowrap;"><?php echo $tr->translate("REQUEST_DATE");?> :</td>
											<td style="text-align: right;white-space:nowrap;"><?php echo date("d-M-Y",strtotime($this->product[0]['date_request']));?></td>
										</tr>
									</table>
								</td>
		                </tr> 
		                 
		            </tbody></table>
		        </td>
		    </tr>
		</table>
		<div class="table-responsive">
		<table width="100%">
		    <tr>
		    	<td id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-family: 'Khmer OS Battambang'; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
						 <tr style="background:#ccc !important;">
							 	<td rowspan="3"  align="center" class="center backgroundcc"><?php echo $tr->translate("NUM");?></td>
								<td rowspan="3"  align="center" class="center backgroundcc"><?php echo $tr->translate("ITEM_DESCRIPTION");?></td>
								<td rowspan="3" class="center backgroundcc"><?php echo $tr->translate("QTY");?></td>
								<td rowspan="3" class="center backgroundcc"><?php echo $tr->translate("MEASURE");?></td>
								<?php foreach($this->su_id as $key => $rss){ $i = $key+1; ?>
								<td class="center backgroundcc" style="white-space:nowrap;" colspan="3">&nbsp;&nbsp;&nbsp;&nbsp;Quaotation <?php echo $db->integerToRoman($i);?> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VAT (<?php if($rss["is_vat"]==1){ echo "10%";}else{echo "N/A";}?>)&nbsp;&nbsp;&nbsp;&nbsp;</td>
								<?php }?>
							</tr>
							<tr style="background:#ccc !important;" class='backgroundcc'>
								<?php foreach($this->su_id as $key => $rss){ $i = $key+1; ?>
									<th colspan="3"  style=" line-height:17px;" class="center backgroundcc"><?php echo $rss["v_name"]?><br /><?php echo $rss["v_phone"]?></th>
								<?php }?>
							</tr>
							<tr style="background:#ccc !important;" class='backgroundcc'>
								<?php foreach($this->su_id as $key => $rss){ $i = $key+1; ?>
									<td style="white-space:nowrap;" class='backgroundcc'>&nbsp;<?php echo $tr->translate("UNIT_PRICE_MEASURE");?></td>
									<td style="white-space:nowrap;" class='backgroundcc'>&nbsp;<?php echo $tr->translate("BRAND");?></td>
									<td style="white-space:nowrap;" class="center backgroundcc"><?php echo $tr->translate("PRODUCT_FROM");?></td>
								<?php }?>
							</tr>
		                <?php 
						$grand_total = 0;
							$total_vat =0;
							foreach($this->product as $key => $rs){$count=count($this->product); $i= $key+1; $index= $key+1;
						?>
						<tr style="line-height:3០px;">
							<td style="white-space:nowrap; width:3%" class="center"><?php echo $i;?></td>
							<td style="white-space:nowrap;">&nbsp;&nbsp;<?php echo $rs["item_name"];?></td>
							<td style="white-space:nowrap;">&nbsp;&nbsp;<?php echo $rs["qty"];?></td>
							<td style="white-space:nowrap;">&nbsp;&nbsp;<?php echo $rs["measure"];?></td>
							<?php 
								$product = $db->getProCompare($this->id,$rs["id"]);
								foreach( $product as $key => $rss){ 
									if($rss["is_check"]==1){
										$check = 'checked="checked"';
										$color = "background:#ccc !important;";
										$vat = (($rs["qty"] * $rss["price"])*  $rss["vat"])/100;
										$grand_total = $grand_total + ($rs["qty"] * $rss["price"])+$vat;
										$total = $total + ($rs["qty"] * $rss["price"]);
										$total_vat = $total_vat + $vat;
									}else{
										$check = '';
										$color="";
									}
									$j = $key+1;
							?>
								<!--<td style="white-space:nowrap;" class="center"><span style="padding:5px 15px; "><?php echo $rss["price"]?></span><span style="margin-top:10px"><input type="checkbox"  value="1" <?php echo $check;?> name="checkbox_<?php echo $i?>_<?php echo $j;?>"/></span></td>-->
								<td style="white-space:nowrap; <?php echo $color;?>">&nbsp;&nbsp;$<span style="float:right;"><?php echo $rss["price"]; ?></span>&nbsp;&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $rss["pro_brand"];?>&nbsp;</td>
								<td style="white-space:nowrap;">&nbsp;<?php echo $rss["pro_from"];?>&nbsp;</td>
							<?php 
							} ?>
						</tr>
							<?php } ?>
							
						<?php if($count<8){
							$loop = 8 - $count;
							for($i=1;$i<=$loop;$i++){
						?>
								<tr class='hover' style="border:1px solid #000;">
							   <td align="center">&nbsp;<?php echo $index+$i?></td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td align="center">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td style="white-space: nowrap;">&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							   <td>&nbsp;</td>
							</tr>
						<?php 
								
							}
						}
						?>
						<tr>
							<td  colspan="13" rowspan="3" style="text-align:right;border-top:1px solid #000;border-left:1px solid #fff;border-bottom:1px solid #fff;">
								<table style="font-size:12px;">
									<tr>
										<th style="white-space: nowrap;"><?php echo $tr->translate("REASON_FROM_COMPAE");?>:</th>
										<td><?php echo $this->su_id[0]["remark"];?></td>
									</tr>
								</table>
							</td>
							<td colspan="2" style="text-align:right;"><?php echo $tr->translate("TOTAL");?>&nbsp;&nbsp;</td>
							<td>&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format($total,2);?></span></td>
						</tr>
						
						<tr>
							<!--<td  colspan="13" style="text-align:right;border-top:1px solid #000;border-left:1px solid #fff;border-bottom:1px solid #fff;"></td>-->
							<td colspan="2" style="text-align:right;white-space: nowrap;"><?php echo $tr->translate("TAX");?>&nbsp;&nbsp;</td>
							<td>&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format($total_vat,2);?></span></td>
						</tr>
						<tr>
							<!--<td  colspan="13" style="text-align:right;border-top:1px solid #000;border-left:1px solid #fff;border-bottom:1px solid #fff;"></td>-->
							<td colspan="2" style="text-align:right;white-space: nowrap;"><?php echo $tr->translate("GRAND_TOTAL");?>&nbsp;&nbsp;</td>
							<td>&nbsp;&nbsp;$<span style="float:right;"><?php echo number_format($grand_total,2);?></span></td>
						</tr>
		                </tbody>
		           </table>
		              <table align="center" width="100%" style="margin-top:5px;font-family: 'Khmer OS';" >
						   <tbody>
						   <!--<tr>
							<td colspan="7">
								<table style="font-size:12px; width:100%">
									<tr style="border: 1px solid #000;">
										<th style="width:5%;white-space: nowrap;">មូលហេតុ:<span style="width:100%; border-bottom:1px dotted #000; "></span>  </th>
										<td ><p style="border-bottom:1px dotted #000; width:100%;margin-top:15px;"><?php echo $this->su_id[0]["remark"];?></p></td>
									</tr>
									<!--<tr>
										<td colspan="2"> សូមលោកប្រធានផ្នែកផ្គត់ផ្គង់ផ្តល់ពត៌មាន  នូវរយៈពេលដែលសម្ភារមកដល់ក្រុមហ៊ុន ឬ អ្នកស្នើសម្ភារ។</td>
									</tr>
								</table>
							</td>
						   </tr>-->
						   <tr style="font-size: 12px;">
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">អនុម័ត<br /> អគ្គនាយក</td>
						        <td></td>
								 <!--<td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'">ឯកភាព<br /> ប្រធានរដ្ខបាល</td>
						        <td></td>-->
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("AGREE_WITH");?><br /><?php echo $tr->translate("BUYER_MANAGER");?></td>
						        <td></td>
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("PREPARE_BY");?><br /><?php echo $tr->translate("STAFF_BUYER");?></td>
						   </tr>
						    <tr style="font-size: 12px; height: 75px;">
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
								<!--<td valign="bottom" style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'; white-space: nowrap;"><hr color="black"/></td>
						        <td></td>-->
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						   </tr>
						   <tr>
								<td style="text-align:center;font-family:'Khmer OS Muol Light';">ឃុត  មករា</td>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	var printContents = document.getElementById('divPrint').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
}
</script>