<?php 
	$url_new = $this->url(array('module'=>'billing','controller'=>'trucktype','action'=>'edit',));
	$url_cancel = $this->url(array('module'=>'billing','controller'=>'trucktype','action'=>'index',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("CATEGORY");?></title>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("ADD_TRUCK_TYPE");?>
			</div>
			<div class="tools"  >
				<a  href="<?php echo $url_cancel;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body ">
					<div>
					 
							<div class="form-group">
							   <label class="col-md-2 control-label"></label>
								<label class="col-md-2 control-label"><?php echo $tr->translate("NAME_KH");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('truck_ca_kh');?>
								</div>
								<label class="col-md-4 control-label"></label>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"></label>
								<label class="col-md-2 control-label"><?php echo $tr->translate("NAME_EN");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('truck_ca_en');?>
								</div>
								<label class="col-md-4 control-label"></label>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"></label>
								<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('remark');?>
								</div>	
								<label class="col-md-4 control-label"></label>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"></label>
								<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('status');?>
								</div>
								<label class="col-md-4 control-label"></label>
							</div>
						<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
								    <a href="<?php echo $this->baseUrl();?>/billing/trucktype"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
									<button type="submit" name="saveclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</label>
							</div>
				
					</div>
				</div>
			</form>
		</div>
	</div>
</div>