<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$form = $this->form_sale;
?>
<title><?php echo $tr->translate("APPROVALE_LIST");?></title>
<div class="row">
<marquee style="margin-top:-20px;" behavior="scroll" direction="left" onmouseout="this.start()" onmouseover="this.stop()" scrollamount="5">យើងត្រូវការ ការយល់ព្រមពី ផ្នែកគណនេយ្យ /ហិរញ្ញវត្ថុ ឫអ្នកដែលមានសិទ្ធ ដើម្បី <span style="color:red;">បង្កើតជាវិក័យបត្រ និង របាយការណ៏ប្រគល់ទំនិញ</span> / We need approval from  or person who have permission to <span style="color:red;">issue invoice and Delivery Report</span> ! </marquee>
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("APPROVALE_LIST");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	 <?php $url_submit = $this->url(array('module'=>'sales','controller'=>'invoiceapprove','action'=>'approved'));?>
	<form id="form_sample_2" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">		   
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
							<tr style="margin-bottom:10px;"> 
								<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:22px; margin-top:20px; font-family:'Khmer OS Muol Light',serif,header-font; "><?php echo $tr->translate("INVOICE");?></li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
									<!--<div  style=" border:1px solid #000; border-radius:5px !important;line-height: 11px;padding: 5px 5px">
										<p>????????? ??????????? </p><p>????????????? ?????????????????</p>
									</div>-->
								</td>
							</tr>
					</table>
		        </td>
		    </tr>
			<tr>
				<td colspan="3"><br />
					<div class="form-group">
												
												<label class="control-label col-md-2">
													<?php echo $tr->translate("INVOICE_NO");?>
												<span class="required">
													 </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php echo $form->getElement("invoice_no");?>
													</div>
												</div>
												<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_DATE");?><span class="required">
												* </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php echo $form->getElement("invoice_date"); ?></div>
												</div>
												
											</div>
											<div class="form-group">
												<label class="control-label col-md-2"><?php echo $tr->translate("INVOICE_METHOD");?><span class="required">
												* </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php echo $form->getElement("inovice_method"); ?></div>
												</div>
												<label class="control-label col-md-2"><?php echo $tr->translate("CUSTOMER");?><span class="required">
												* </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php echo $form->getElement("customer_id"); ?></div>
												</div>
											</div>
											
											<div class="form-group">
												<label class="control-label col-md-2"><?php echo $tr->translate("DN_NO");?><span class="required">
												* </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php echo $form->getElement("dn_no"); ?></div>
												</div>
												<label class="control-label col-md-2"><?php echo $tr->translate("BRANCH");?><span class="required">
												* </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php echo $form->getElement("branch_id"); ?></div>
												</div>
											</div>
											
											<div class="form-group">
												<label class="control-label col-md-2"><?php //echo $tr->translate("DN_NO");?><span class="required">
												* </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php //echo $form->getElement("dn_no"); ?></div>
												</div>
												<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
												* </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php echo $form->getElement("remark"); ?></div>
												</div>
											</div>
											
											<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php //echo $tr->translate("CHECK");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("DATE");?></th>
									<th><?php echo $tr->translate("DN_NO");?></th>
									<th><?php echo $tr->translate("TOTAL");?></th>
									<th><?php echo $tr->translate("DISCOUNT");?></th>
									<th><?php echo $tr->translate("PAID");?></th>
									<th><?php echo $tr->translate("BALANCE");?></th>
							</tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
					</div>
					<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<label class="control-label col-md-2">
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("ជំពាក់សរុប​ :");?> Total<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left">
								<i style="margin-top: 6px;">$</i>
								<?php echo $form->getElement("all_total");?>
								<?php echo $form->getElement("balance");?>
								<?php echo $form->getElement("paid");?>
								</div>
							</div>
						</div>
						<!--<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("ប្រាក់បានបង់សរុប");?> (Paid)
							</label>
							<div class="col-md-4">
								<div class="input-icon left">
								<i style="margin-top: 6px;">$</i>
									<?php echo $form->getElement("paid");?>
								</div>
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ពន្ធ");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php //echo $form->getElement("total_tax");?>
								</div>
							</div>
							<label class="control-label col-md-2">ប្រាក់នៅសល់ (Balance)​ :<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left">
								<i style="margin-top: 6px;">$</i>
								<?php echo $form->getElement("balance");?>
								</div>
							</div>
						</div>-->
				</td>
			</tr>
		    <tr>
		    	<td id="exportExcel"><br />
		            <table  style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0" border="1">
						<tbody>
						</tbody>
		           </table>
				</td>
		    </tr>
			</tbody>
		</table>
		</div><!-- end print -->
		<div class="form-group">
			<div  class="col-md-12 col-md-offset-4 col-md-8">
				<label class="col-md-3 control-label"><a href="<?php echo $this->baseUrl();?>/sales/invoiceapprove/" ><button style="width:90%;" type="button" class="btn blue btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a></label>
				<div class="col-md-3 control-label"><button type="submit" name="print" value="print" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button></div>
		        <!--<div class="col-md-4 control-label"><button type="submit" name="saveprint" value="saveprint" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_PRINTINVOICE")?></button></div>-->
			</div>
		</div>
		</form>	
		
		
		
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>

$(document).ready(function() { 
   
  calculateBalance();
 }); 
function checkpayment(){
	payment_id = $("#inovice_method").val();
	//alert(payment_id);
	if(payment_id==2){
		$( "#bank_name" ).attr( "readOnly", false );
		$( "#cheque" ).attr( "readOnly", false );
	}else{
		$( "#bank_name" ).attr( "readOnly", true );
		$( "#cheque" ).attr( "readOnly", true );
	}
}
function checkControll(){
	$("#table_order").html("");
	$("#identity").val('');
	$("#customer_id" ).val('');
	$("#dn_no" ).val('');
	$('#balance').val(0);
	$('#all_total').val(0);//$('#paid').val(0);
	payment_method = $("#inovice_method").val();
	if(payment_method==1){
		$( "#dn_no" ).attr( "readOnly", true );
		
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		$( "#customer_id" ).attr( "readOnly", true );
		$( "#dn_no" ).attr( "readOnly", false );
    }
}
<?php $urlgetinvoice =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'getdn')); ?>
function getInvoice(type){
	if(type==1){
		post_id=$("#customer_id").val();
		$( "#dn_no" ).attr( "readonly", true );
		$( "#customer_id" ).attr( "readOnly", false );
	}else{
		post_id=$("#dn_no").val();
		$( "#customer_id" ).attr( "readonly", true );
		$( "#dn_no" ).attr( "readOnly", false );
	}
	$.ajax({
			url:"<?php echo $urlgetinvoice;?>",
			type:"post",
			data:{'post_id':post_id,'type_id':type},
			success: function(data){
				//alert(data);
				$("#table_order").html("");
				template='<tr height="33px">';
					template+='<th><?php echo $tr->translate("DEL");?></th>';
					template+='<th><?php echo $tr->translate("NUM");?></th>';
					template+='<th><?php echo $tr->translate("DN_NO");?></th>';
					template+='<th style="white-space:nowrap;"><?php echo $tr->translate("DN_DATE");?></th>';
					
					template+='<th><?php echo $tr->translate("GRAND_TOTAL");?></th>';
					//template+='<th><?php echo $tr->translate("បញ្ចុះតម្លៃ");?></th>';
					template+='<th><?php echo $tr->translate("TOTAL_PAYMENT");?></th>';
					template+='<th><?php echo $tr->translate("BALANCE");?></th>';
				template+='</tr>';
				
				$('#identity').val("");
				data = $.parseJSON(data);
				
				
				for(i=0;i<data.length;i++){
					if(i==0){
						$("#customer_id").val(data[i].customer_id);
						$("#customer_id").select2();
					}
					index=i+1;
					template+='<tr style="height:30px;">';
			            //template+='<td ><img onClick="deleteRecord('+index+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
						template+='<td style="vertical-align: middle;text-align: center;"><input type="checkbox" onClick="checkedRow('+index+')" name="checkbox_'+index+'" id="checkbox_'+index+'" /></td>';
						template+='<td >'+index+'</td>';
						template+='<td >'+data[i].deliver_no+'</td>';
						template+='<td >'+data[i].deli_date+'<input type="hidden" value='+data[i].id+' id="invoice_no'+index+'" name="invoice_no'+index+'"/><input type="hidden" value='+data[i].so_id+' id="sale_id'+index+'" name="sale_id'+index+'"/></td>';
						//template+='<td >'+data[i].receive_invoice_date+'<input type="hidden" value='+data[i].net_total+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
						//template+='<td >'+data[i].invoice_controlling_date+'<input type="hidden" value='+data[i].discount_after+' id="discount'+index+'" name="discount'+index+'"/></td>';
						template+='<td style="">$<span style="float:right;">'+data[i].all_total+'&nbsp;&nbsp;</span><input type="hidden" value='+data[i].all_total+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
						template+='<td >$<span style="float:right;">'+data[i].paid+'&nbsp;&nbsp;</span><input type="hidden" value="0" id="paid_amount'+index+'" name="paid_amount'+index+'" value="'+data[i].paid+'"/></td>';
						template+='<td >$<span style="float:right;">'+data[i].all_total_after+'&nbsp;&nbsp;</span><input type="hidden" value='+data[i].all_total_after+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
				    template+="</tr>";
					
					/*if($('#identity').val()!="") {
						var identity = $('#identity').val();
						$('#identity').val(identity+','+index);
					} else {$('#identity').val(index);}*/
				}
				$('#table_order').append(template);
				if(data.length>0){netTotal();}else{$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");}
				
			},
			error:function(e){
				alert("error"+e);
			}
		});	
}
function checkedRow(index){
	var ids =$('#identity').val();
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {//calculate record row
			if(arrays[i] == index) arrays.splice(i,1);
			if($('#checkbox_'+index).attr('checked')){
				if($("#identity").val()!="") {
					$("#identity").val(ids+','+index);
				}else { 
					$("#identity").val(index);
				}
				
			 }else{
				var strings = arrays.join(',');
				$('#identity').val(strings);
			}
		}
		
		netTotal();
}
function netTotal() {//use
	var subtotal=0;
	var paid = 0;
	discount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		//subtotal += Number($('#subtotal'+rowIDArray[n]).val());
		//paid +=Number($('#paid_amount'+rowIDArray[n]).val());
		//discount +=Number($('#discount'+rowIDArray[n]).val());
		subtotal += Number($('#balance_after'+rowIDArray[n]).val());
		
	}
	//var alltotal = Number(subtotal - discount).toFixed(2);
	$('#all_total').val(subtotal.toFixed(2));
	$('#paid').val(subtotal.toFixed(2));
	//$('#paid').val(0);
	doRemain();
}
function doRemain() {
	var all_total = Number($('#all_total').val());
	var paid = Number($('#paid').val());
	if(paid > all_total){
		var paid = $('#paid').val(all_total.toFixed(2));
		 $('#remain').val(0);
   }else{
	   remain = all_total-paid;
	   $('#balance').val(remain.toFixed(2));
	}	
}
function calculateBalance(){
	deposit= $("#deposit").val();
	net_total = $('#net_total').val();
	balance = net_total-deposit;
	if(balance<0){
		balance=0;
		$("#deposit").val(net_total);
	}
	$("#balance").val(balance);
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
