<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("INVOICE");?></title>
<style>
	ol.term{margin-left:30px;!important}
</style>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("INVOICE");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<!--<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>-->
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%; margin-top:15px;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 0px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
							<tr style="margin-bottom:10px;"> 
								<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:22px; margin-top:20px; font-family:'Khmer OS Muol Light',serif,header-font; "><?php echo $tr->translate("INVOICE");?></li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
									<!--<div  style=" border:1px solid #000; border-radius:5px !important;line-height: 11px;padding: 5px 5px">
										<p>????????? ??????????? </p><p>????????????? ?????????????????</p>
									</div>-->
								</td>
							</tr>
						 
						
		                <tr>
		                	<td colspan="3" valign="top"><br />
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody>
		                			
		                			<tr>
		                				<td style="font-size: 11px;" valign="top" width="30%;">
		                				<!--<div style="width:100%; background: #244456;display: block;color:#fff;margin-top: 10px;">&nbsp;&nbsp;Customer Info</div>-->
										<table width="100%" style="font-size: 12px; font-weight:600;line-height:25px;">
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("COMPANY_NAME");?> </td>
													<td style="text-align: left;white-space: nowrap;">: <?php echo $this->product[0]['customer_name'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("ADDRESS");?> </td>
													<td style="text-align: left;white-space: nowrap;"> :<?php echo $this->product[0]['address'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("CONTACT_NAME");?> </td>
													<td style="text-align: left;white-space: nowrap;"> : <?php echo $this->product[0]['contact_name'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("PHONE");?> </td>
													<td style="text-align: left;white-space: nowrap;"> : <?php echo $this->product[0]['phone'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("EMAIL");?> </td>
													<td style="text-align: left;white-space: nowrap;"> :<?php echo $this->product[0]['email'];?></td>
												</tr>
											</table>
		                				</td>
		                				<td width="40%"></td>
		                				<td width="30%" style="text-align: left;font-size: 11px;" valign="top" >
		                					<!--<div style="padding-left: 10px;width:100%; background: #244456;display: block;color:#fff;margin-top: 10px;">&nbsp;&nbsp;Quotation</div>-->
		                					
											<table width="100%" style="font-size: 12px; font-weight:600; line-height:25px;">
												
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("INVOICE_NO");?> </td>
													<td style="text-align: left;white-space: nowrap;"> : <?php echo $this->product[0]['invoice_no'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("INVOICE_DATE");?> </td>
													<td style="text-align: left;white-space: nowrap;"> : <?php echo date("d-M-Y",strtotime($this->product[0]['invoice_date']));?></td>
												</tr>
											</table>
											
		                				</td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:13px; !important" width="100%" cellspacing="0">
		                 <tbody>
		                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 40px; font-size:13px !important; padding:1px 0px; white-space: nowrap; ">
		                    <th width="5%"><?php echo $tr->translate("NUM");?></th>
							<th><?php echo ($tr->translate("ITEM_CODE"));?></th>
							<th><?php echo ($tr->translate("ITEM_NAME"));?></th>
							<th><?php echo ($tr->translate("QTY"));?></th>
							<th><?php echo ($tr->translate("MEASURE"));?></th>
							<th><?php echo ($tr->translate("PRICE"));?></th>
							<th><?php echo ($tr->translate("TOTAL_PRICE"));?></th>
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
						$inx=0;
						$sub_total=0;
						$count = count($this->product);
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){ 
							$inx = $index+1;
							$total_price = $rs["price"]*(($rs["price"]*$rs["benefit_plus"])/100);
							
							$sub_total = $sub_total + $total_price*$rs["qty"];
						?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["qty"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["measure"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<span>$</span><span style="float:right;"><?php echo number_format($total_price,2);?></span></td>
						   <td>&nbsp;<span>$</span><span style="float:right;"><?php echo number_format($rs["qty"]*$total_price,2);?></span></td>
						</tr>
						   <?php 
                    }?>
					<?php if($count<10){
						$loop = 10 - $count;
						for($i=1;$i<=$loop;$i++){
					?>
						<tr class='hover' style="border:1px solid #000;">
						   <td align="center">&nbsp;<?php echo $inx+$i?></td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td>&nbsp;</td>
						   <td>&nbsp;</td>
						   <td>&nbsp;</td>
						</tr>
					<?php 
							
						}
					}
					?>
                    <tr>
						<td colspan="5" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td colspan="1" style="border-left:1px solid #000;">&nbsp;&nbsp;<?php echo $tr->translate("TOTAL");?></td>
						<td >&nbsp;&nbsp;<span>$</span><span style="float:right;"><?php echo number_format($sub_total,2);?></span></td>
					</tr>
					<!--<tr>
						<td colspan="7" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td colspan="1" style="border-left:1px solid #000;">&nbsp;&nbsp;<?php echo $tr->translate("DISCOUNT");?></td>
						<td >&nbsp;&nbsp;<span>$</span><span style="float:right;"><?php echo number_format(0,2);?></span></td>
					</tr>
					<tr>
						<td colspan="7" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td colspan="1" style="border-left:1px solid #000;">&nbsp;&nbsp;<?php echo $tr->translate("TOTAL_AMOUNT");?></td>
						<td >&nbsp;&nbsp;<span>$</span><span style="float:right;"><?php //echo number_format($this->product[0]['balance'],2);?></span></td>
					</tr>-->
					
					<!--<tr>
						<td colspan="6" style="border:1px solid #fff;border-top:1px solid #000;">
						<p style="margin-top: 10px;font-size: 13px !important;"><strong  ><u><?php echo $tr->translate("TERM_CONDICTION");?></u></strong></p>
							<style>
								ul.term li{ line-height: 20px;list-style-type: none; font-size: 13px !important;}
							</style>
							<ol class="term" style=" margin-top: -6px;">
								<?php  if(!empty($this->term)){ foreach($this->term as $rs){?>
								<li><?php echo $rs["title"]?></li>
								<!--<li>Delivery : Free delivery</li>
								<li>Payment : Payment shall not be later than 1 month following the delivery date.<br />The compay keeps the right to suspend the product delivery in case of unacceptable late payment.</li>
								<li>Validity : This quotation shall be valid within 1 month following the quotation date.</li>
								
								<?php }}?>
							</ol>
						</td>
					</tr>-->
					
		            </tbody>
		           </table>
		             
					  
		             <table align="center" width="100%"style="margin-top:5px;" >
						   <tbody>
						   <tr>
							<td colspan="7" style="margin-button:5px;">
								<table style="font-size:10px; width:100%">
									<tr>
										<td style="width:8%"><?php echo $tr->translate("NOTE");?> :</td>
										<td style=""><p style="padding: 7px 0 0 0;line-height: 14px;border-bottom:1px dotted #000;"><?php //echo $this->product[0]["remark"]?>&nbsp;</p></td>
									</tr>
									
								</table>
							</td>
						   </tr>
						   <tr style="font-size: 12px; margin-top:10px;">
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'; ">អនុម័ត<br />អគ្គនាយក</td>
						        <td></td>
								 <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'; ">អតិថិជន</td>
						        <td></td>
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';">ត្រួតពិនិត្យដោយ</td>
						        <td></td>
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';">គណនេយ្យករ</td>
						   </tr>
						    <tr style="font-size: 12px; height: 75px;">
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
								 <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						   </tr>
						   <tr style="font-size: 12px;">
						        <td style="text-align:center;font-family:'Khmer OS Muol Light';">ឃុត  មករា</td>
						   </tr>
						</tbody>
					</table>
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
