<?php 					
	$url_new = $this->url(array('module'=>'sales','controller'=>'quoatation','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	function secondsToTime($seconds) {
	$dtF = new DateTime("@0");
	$dtT = new DateTime("@$seconds");
	return $dtF->diff($dtT)->format('%a');
}
?>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("QUOTATION_LIST");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
			</div>
			<div class="portlet-body form">
				<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch_id');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('customer_id');?></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>		
				</form> 
					<div class="contain_form" style="clear: both;">
						<form name="list"><div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
					<table class="collape tablesorter" id="table" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NUM");?></th>
								<th class="tdheader"><?php echo  $tr->translate("QUOTATION_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("QUOATATION_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("CUSTOMER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("LOCATION_NAME");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TOTAL");?></th>
								<th class="tdheader"><?php echo  $tr->translate("VALID_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("APP_STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PEDDING");?></th>
								<th class="tdheader"><?php echo  $tr->translate("USER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "table";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($this->rs)){
								foreach ($this->rs as $key=>$rs){
									$edit_status = '';
									if($rs["pedding_stat"]>1 and $rs["appr_stat"]!=2){
										$edit_status = "style='pointer-events: none;cursor: default;color: #ccc;'";
									}
									$date_now =  date("Y-m-d");
									
									$valid_date = strtotime($rs["valid_date"])-strtotime($date_now);
									$valid_day = secondsToTime($valid_date);
									$color='';
									if($valid_day <=7){
										$color = "style='background:rgba(255, 0, 0, 0.32)'";
									}
							?>
								<tr class="normal" <?php echo $color;?>>
									<td class="items-no"><?php echo $key+1;?> </td>
									<td class="items"><?php echo $rs["quoat_number"];?></td>
									<td class="items"><?php echo $rs["date_order"];?></td>
									<td class="items"><?php echo $rs["customer_name"];?></td>
									<td class="items"><?php echo $rs["branch"];?></td>
									<td class="items"><?php echo $rs["all_total"];?></td>
									<td class="items"><?php echo $rs["valid_date"];?></td>
									<td class="items"><?php echo $rs["appr_status"];?></td>
									<td class="items"><?php echo $rs["pedding"];?></td>
									<td class="items"><?php echo $rs["user_name"];?></td>
									<td class="items-no" style="white-space: nowrap;">
										<a <?php echo $edit_status;?> href="<?php echo $this->baseUrl();?>/sales/quoatation/edit/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("EDIT");?></a> | 
										<a <?php echo $edit_status;?> href="<?php echo $this->baseUrl();?>/sales/quoatation/renewquote/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("RENEW");?></a> |
										<a target="_blank" href="<?php echo $this->baseUrl();?>/sales/quoatation/purproductdetail/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("PRINT");?></a>
									</td>
								</tr>
							<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table></div></form><?php echo $footer?>
					</div>
		   </div>
		</div>
	</div>
</div>