<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$result = $this->stockin;

$db = new report_Model_DbStock();


?>
<?php $formFilter = $this->formFilter; ?>
<title><?php echo $tr->translate("STOCK_SUMMARY");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("STOCK_SUMMARY");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							    <?php echo $tr->translate("ACTIONS");?> <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;<?php echo $tr->translate("PRINT");?>
										</a>
									</li>
									<li><a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a> </li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" style="border-bottom: 1px solid #ccc;" action="<?php //echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('ad_search');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('branch');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('product_id');?></label>
					<!--  product_id	<label class="control-label col-md-3">
								<select data-placeholder="Select..." class="form-control select2me " style="text-align: left;" id="add_item" name="add_item" >
								<?php echo $this->items; ?>
								</select>
					-->
						</label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('category');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('suppliyer_id');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('start_date');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('end_date');?></label>
						<label class="control-label col-md-3 pull-right">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:25 0 0 0; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
		<style>
			.style{
					line-height: 20px;font-size: 9px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
				th{padding: 0px;}
				table tbody tr th{
					line-height:30px;
					background:#ccc;
					font-size:15px;
					padding:3px;
				}
				table tr td{
					font-size:12px;
				}
				ul.pur_info li{line-height:18px; 
						font-weight: normal !important;}
				ul.pur_info li strong{font-weight: bold;}
			   .hover:hover{background: #ccc;}
				table.collape td{border: 1px solid #000 !important;}
				
               #nobor{border-left: 1px solid #fff !important;border-top: 1px solid #fff !important;
					border-right: 1px solid #fff !important;}
				
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
		
		</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
		                	<td width="60%" valign="top">
								<ul>
									<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
									<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
		                			<li style="text-align:center; font-size:18px;margin: 10px 0px 0px 0px;font-family:'Khmer OS Muol Light',serif,header-font;"> <?php echo $tr->translate("STOCK_SUMMARY");?></li>
		                			
		                			<li style="text-align:center; font-size:14px;margin: 10px 0px 0px 0px;font-family:'Khmer OS Muol Light',serif,header-font;"> 
		                			         <?php if(!empty($this->search['category']))
		                			         	foreach ($this->cat As $c){
			                			         	if ($this->search['category']==$c['id']){
			                			         		echo $tr->translate("ផ្នែក")."&nbsp;".$c['name'];
			                			         	}
		                			             }
		                			         	?></li>
		                			
									<li style="text-align:center; font-size:13px;"><?php echo date("d-M-Y",strtotime($this->start_date));?> ដល់ <?php echo date("d-M-Y",strtotime($this->end_date));?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td width="65%"></td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
						</tbody>
					</table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" >
		            <table  class="collape tablesorter" style="border-collapse:collapse; font-size:12px;" width="100%" cellspacing="0" border="1">
		                 <tbody>
						  <?php $num=1; 
			               $total_pur_qty = 0;
						   $total_begin_qty =0;
						   $toal_issus_qty =0;
						   $total_edning_qty = 0;
						   $total_price =0;
						   $total_amount = 0;
						   $total_adjust=0;
						   if(!empty($this->stockin))foreach ($this->stockin AS $index => $rs){
							   $rs_re = $db->getReceiveByPro($rs["id"],$this->search);
								$rs_deli = $db->getDeliByPro($rs["id"],$this->search);
								$adjust=$db->getAdjustPro($rs["id"],$this->search);
								
								$pur_qty = $rs_re["qty_receive"];
								$issuse_qty = $rs_deli["deli_qty"];
							    $total_pur_qty =  $total_pur_qty+ $pur_qty;
							    $toal_issus_qty =  $toal_issus_qty+ $issuse_qty;
							    $total_adjust =  $total_adjust+ $adjust['adjust_qty'];
							    
								$total_begin_qty =  $total_begin_qty+ (($rs["qty"]+$issuse_qty)-$pur_qty);
							    $total_price =  $total_price+$rs["price"];
							    $total_edning_qty =$total_edning_qty+$rs["qty"];
							   $total_amount= $total_amount+$rs["price"]*$rs["qty"];
							   
						   }
						  ?>
						  <thead>
						 <tr  >
						   <td align="center" style="white-space: nowrap;text-align:center;" id="nobor">&nbsp;</td>
						   <td style="white-space: nowrap;text-align:center; " id="nobor">&nbsp;</td>
						   
						   <td style="white-space: nowrap;text-align:center; "  id="nobor">&nbsp;</td>
						   <td style="white-space: nowrap;text-align:center; "  id="nobor">&nbsp;<?php echo $tr->translate("TOTAL");?></td>
						   <td style="white-space: nowrap;text-align:center; "  id="nobor">&nbsp;$<span style="float:right"><?php echo number_format($total_price,2);?></span></td>
						   <td style="white-space: nowrap;text-align:center; "  id="nobor">&nbsp;<?php echo  $total_begin_qty;?></td>
						   <td style="white-space: nowrap;text-align:center; "  id="nobor">&nbsp;<?php echo $total_pur_qty;?></td>
						   <td style="white-space: nowrap;text-align:center; "  id="nobor">&nbsp; <?php echo $toal_issus_qty;?></td>
						   <td style="white-space: nowrap;text-align:center; "  id="nobor">&nbsp; <?php echo $total_adjust;?></td>
						   <td style="white-space: nowrap;text-align:center; "  id="nobor">&nbsp;<?php echo  $total_edning_qty;?></td>
						   <td style="white-space: nowrap; "  id="nobor">&nbsp;$<span>&nbsp;&nbsp;<?php echo number_format($total_amount,2);?></span></td>
						</tr>
						 
							<tr bgcolor="#ccc" class="style tdborder" align="center" style="font-weight:bold; line-height: 35px;border:1px solid #000; font-size:12px; padding:1px 0px; white-space: nowrap; ">
			                    <td class="tdheader">&nbsp;<?php echo $tr->translate("NUM");?></td>
			                   <!-- <td class="tdheader">&nbsp;<?php echo $tr->translate("DATE_IN");?></td> --> 
			                     
								<td class="tdheader"><?php echo $tr->translate("CODE");?></td>
								<td class="tdheader">&nbsp;<?php echo $tr->translate("ITEM_NAME");?></td>
								
							<!-- <td class="tdheader">&nbsp;<?php echo $tr->translate("CATEGORY");?></td> -->	
								
								<td class="tdheader">&nbsp;<?php echo $tr->translate("PACKING");?></td>
								<td class="tdheader"><?php echo $tr->translate("U/PRICE");?></td>
								<td class="tdheader"><?php echo $tr->translate("B/D");?></td>
								<td class="tdheader">&nbsp;<?php echo $tr->translate("PURCH");?></td>
								<td class="tdheader">&nbsp;<?php echo $tr->translate("ISSUS");?></td>
								<td class="tdheader">&nbsp;<?php echo $tr->translate("ADJUST");?></td>
								<td class="tdheader">&nbsp;<?php echo $tr->translate("E/D");?></td>
								<td class="tdheader" >&nbsp;<?php echo $tr->translate("AMOUNT");?></td>
			                </tr> 
			             </thead>
		                
		                <?php 
							if(!empty($this->stockin))foreach ($this->stockin AS $index => $rs){
								$rs_re = $db->getReceiveByPro($rs["id"],$this->search);
								$rs_deli = $db->getDeliByPro($rs["id"],$this->search);
								$adj=$db->getAdjustPro($rs["id"],$this->search);
								 
								$pur_qty = $rs_re["qty_receive"];
								$issuse_qty = $rs_deli["deli_qty"];
								
								$begin_qty = ($rs["qty"]+$rs_deli["deli_qty"])-$rs_re["qty_receive"];
								$total_price = $total_price+$rs["price"];
						?>
						<tr class='tdborder row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1;?></td>
						  <!-- <td style="white-space: nowrap;">&nbsp;<?php if(!empty($rs["date_order"])) echo date("d-M-Y",strtotime($rs["date_order"]));?></td> --> 
						    
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="max-width: 200px !important;">&nbsp;<?php echo $rs["item_name"];?></td>
						 <!--  <td style="max-width: 200px !important;">&nbsp;<?php //echo $rs["cat_name"];?></td> --> 
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["measure"];?></td>
						   <td style="white-space: nowrap;">&nbsp;$<span style="float:right;"><?php echo number_format($rs["price"],2);?></span></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $begin_qty;?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo  $pur_qty;?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo  $issuse_qty;?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo  $adj['adjust_qty'];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["qty"];?></td>
						   <td>&nbsp;$<span >&nbsp;&nbsp;<?php echo number_format($rs["price"]*$rs["qty"],2);?></span></td>
						</tr>
						<?php 
							 
						}?>
		                </tbody>
		           </table>
		            <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">Received by</td>
						        <td></td>
								<td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">Approved by</td>
								<td></td>
								<td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">Checked by</td>
								<td></td>
								<td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer OS Muol Light'">Prepared by</td>
						   </tr>
						</tbody>
					</table>	
		         </td>  
		             
		    		 
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
						
function doPrint() {
	var printContents = document.getElementById('divPrint').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
}
</script>
