<?php 					
	$url_new = $this->url(array('module'=>'billing','controller'=>'billingproduct','action'=>'add',),null,true);
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	//print_r($this->rs);
?>
<title><?php echo $tr->translate("MENU_PURCHASE_ADVANCE_INDEX");?></title>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("LIST_PRODUCT");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
			</div>
			<div class="portlet-body form frmfilter">
					<form method="post" action="">
					    <label class="col-md-4 control-label"><?php echo $formFilter->getElement('search_name');?></label> 
					    <label class="col-md-4 control-label"><?php echo $formFilter->getElement('status_serach');?></label> 
					    <label class="col-md-2control-label"> <button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button> </label> 
					</form> 
        	 </div>
        	 <?php echo $this->list; ?>
		</div>
	</div>
	
</div>
