<?php 
	$url_new = $this->url(array('module'=>'sales','controller'=>'plan','action'=>'add',));
	$url_edit = $this->url(array('module'=>'sales','controller'=>'plan','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'sales','controller'=>'plan','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->formFilter;
	$formFilter = $this->formFilter;
	$rs = $this->product;
	 
?>
<title><?php echo $tr->translate("PRODUCT_LIST");?></title>

	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PLAN");?>
			</div>
			
			<div class="caption pull-right">
				<a href="<?php echo $url_new;?>"><button id="sample_editable_1_new" class="btn green">Add New <i class="fa fa-plus"></i></button></a>
			</div>
			<div class="caption" style="float:right">
					<?php $formList = new Application_Form_Frmlist(); //echo $formList->showAddBuntton($url_new);?>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
					<div class="form-group">
						<div class="col-md-3">
							<input  class="form-control" id="adv_search" name="adv_search" value=" " placeholder="<?php echo $this->translate("Search");?>" type="text" >
						</div>
						
						<div class="col-md-3">
							<?php echo $form->getElement('typecate');?>
						</div>
						
						<div class="col-md-3">
							<?php echo $form->getElement("status");?>
						</div>
						<div class="col-md-3">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("Search");?></button>
						</div>						
					</div>
				</div>
				
			</form>
			
		</div>
		<?PHP echo $this->list ?>
</div>
<script>
$( document ).ready(function() {
    $("#adv_search").val('<?php echo $this->search['adv_search']?>');
    $("#typecate").val('<?php echo $this->search['typecate']?>');
    $("#status").val('<?php echo $this->search['status']?>');
});

</script>