<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'sales','controller'=>'quoatation','action'=>'edit'));
	$url_cancel = $this->url(array('module'=>'sales','controller'=>'index','action'=>'index'));
	$url_new = $this->url(array('module'=>'sales','controller'=>'quoatation','action'=>'edit'));
?>
<title><?php echo $tr->translate("SALE_ORDER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("SALE_ORDER")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
						<i class="fa fa-undo"></i>&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2">
								<?php echo $tr->translate("SALE_NO");?>
							<span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("so_number");?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("SALE_DATE");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<i class="fa fa-calendar"></i><?php echo $form->getElement("order_date");?>
								</div>
							</div>
						</div>
						<div class="form-group" style="display:none;">
							<label class="control-label col-md-2"><?php echo $tr->translate("QUOTATION_NO");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("txt_order"); ?></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DATE_QUOTE");?><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("qouate_date"); ?></div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("CUSTOMER_NAME");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("customer_id");?>
									<?php echo $form->getElement("id");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("BRANCH_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('branch_id');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php  echo $tr->translate("SALE_AGENT");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("saleagent_id");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
							
							
						</div>
						<div class="form-group">
							<div class="col-md-2">
								<button type="button" class="btn red delete" style="width:100%;">
									<i class="fa fa-barcode"></i>
									<span><?php echo $tr->translate("SCAN");?> </span>
								</button>
							</div>
							<div class="col-md-10">
								<!--<select data-placeholder="Select..." class="form-control select2me" id="add_item" name="add_item" Onchange="addRow();"  style="width:100% ;margin:0 auto;">
									<?php echo $this->items; ?>
								</select>-->
								<input type="hidden" class="form-control" id="add_item" name="add_item" Onchange="addRow();" style="width:100%;" placeholder="<?php echo $tr->translate("SELECT_PRODUCT");?>"/>
							</div>
						</div>
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("DEL");?></th>
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
									<th><?php echo $tr->translate("MEASURE");?></th>
									<th><?php echo $tr->translate("CURRENT_QTY");?></th>
									<th><?php echo $tr->translate("QTY_ORDER");?></th>
									<th><?php echo $tr->translate("COST_PRICE");?></th>
									<th style="white-space: nowrap;"><?php echo $tr->translate("BENEFIT_PLUS");?></th>
									<th><?php echo $tr->translate("SUB_TOTAL_CAP");?></th>
							 </tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
						 <input type="hidden" id="identity_term" name="identity_term" />
					  </div>
						<!-- blog bottom -->
						<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("TOTAL");?>
							</label>
							<div class="col-md-4">
								<div class="input-icon left">
									<i style="margin-top: 6px;">$</i>
								<?php echo $form->getElement("totalAmoun");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("DISCOUNT");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left">
									 <i style="margin-top: 6px;"></i>
									<?php echo $form->getElement("dis_value");?>
								       <input type="hidden" name="global_disc" id="global_disc"/>
								</div>
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("TOTAL_AMOUNT");?>​  </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon left">
									 <i style="margin-top: 6px;">$</i>
									<?php echo $form->getElement("all_total");?>
								</div>
							</div>
						</div>
						
					
						
						<div class="form-group">
							
							<div  class="col-md-8 col-md-offset-4 col-md-4">
								<a href="<?php echo $this->baseUrl();?>/sales/makeso/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<!--<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>-->
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
<?php $url_product_option =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'get-product-option')); ?>
function productOption(){
	customer_id=$('#customer_id').val();
	branch_id=$('#branch_id').val();
	//alert(branch_id);
	$.ajax({
						url:"<?php echo $url_product_option;?>",
						type:"post",
						data:{'customer_id':customer_id,'branch_id':branch_id},
						success: function(data){
							//alert(data);
							if(data!=null || data!=""){
								
								item = $.parseJSON(data);		
								//document.getElementById('add_item').innerHTML=item;
								$('#add_item').select2({
									data : _.map(_.range(0, item.length), function (i) {
										//alert(itemss);
										  return {
											  id  : item[i].id,
											  text: item[i].item_code+"-"+item[i].item_name
										  };
									}),
									dropdownCssClass : 'capitalize',
									containerCssClass: 'capitalize',
									// configure as multiple select
									//multiple         : true,
									// text for loading more results
									formatLoadMore   : 'Loading more...',
									query            : function (q) {
									// pageSize is number of results to show in dropdown
										var pageSize,
											results;
											pageSize = 20;
											results  = _.filter(this.data, function (e) {
												return (q.term === "" || e.text.toUpperCase().indexOf(q.term.toUpperCase()) >= 0);
										 });
										q.callback({
											results: results.slice((q.page - 1) * pageSize, q.page * pageSize),
											// retrieve more when user hits bottom
											more   : results.length >= q.page * pageSize
										});
									}
								});
							}else{
								alert("No date in quote");
							}
						},
						error:function(e){
							//alert(e);
						}
				});
	
}

<?php $url_product =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'get-products')); ?>
var index5 = 0;num=0;
var option5 = '<?php echo $this->items; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
var index=1;
function addRow(item_id) {
	customer_id=$('#customer_id').val();
	branch_id=$('#branch_id').val();
	item_id=$("#add_item").val();
	$.ajax({
		url:"<?php echo $url_product;?>",
		type:"post",
		data:{'item_id':item_id,'branch_id':branch_id,'customer_id':customer_id},
		success: function(data){
			//alert(data);
			data = $.parseJSON(data);		
			index5++; //var first = index5;
			index=index+1;
			for(i=1; i<index5; i++){
				new_item=parseInt(item_id);
				items = parseInt($("#item_id_"+i).val());
			}
			template='<tr id="row_order_'+index5+'" style="height:33px;">';
			var inp = '';
			
			template+='<td ><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
			template+='<td  width="1%">'+index5+'</td>';
			template+='<td width="30%">'+data.item_name+" "+data.item_code+'<input type="hidden" name="item_id_'+index5+'" id="item_id_'+index5+'" value="'+data.id+'" /> </td>';
			template+='<td><labe id="lb_measure_'+index5+'">'+data.measure+'</label></td>';
			template+='<td><input style="background:#f5e1e1;" readonly type="text" class="form-control" id="current_qty'+index5+'" name="current_qty'+index5+'" value="'+data.qty+'" /></td>';
			template+='<td><input type="text" onkeyup="calculatePrice('+index5+')" class="form-control" required="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
			template+='<td><div class="input-icon left"><i class="fa">$</i><input style="text-align:right;" type="text" onkeyup="calculatePrice('+index5+')" readOnly="readOnly" required="1" class="validate[required,custom[number]] input form-control" id="price'+index5+'" name="price'+index5+'" value="'+data.price+'" /><input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'" value="'+data.price+'"/></td>';
			template+='<td width="5%"><input type="text" onkeyup="calculatePrice('+index5+')" id="dis_value'+index5+'" name="dis_value'+index5+'" class="form-control" readOnly="readOnly" value="'+data.benefit_plus+'" /><input type="hidden" id="olddis_value_'+index5+'" name="olddis_value_'+index5+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
			template+='<td><div class="input-icon left"><i class="fa">$</i><input style="text-align:right;" type="text" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
			template+="</tr>";
			$('#table_order').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index5);
			} else {$('#identity').val(index5);}
			$("#item_id_"+index5).val(item_id);
			//getQtyById(index5);
			//getProductPrice(item_id,index5);
			$("#paid").val(0);
			$("#row_order_0").remove();
		},
		error:function(e){
							//alert(e);
		}
	});
}

<?php $url_product =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'get-product')); ?>
function getQtyById(index){//use
				item_id=$("#item_id_"+index).val();
				branch_id = $("#branch_id").val();
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				
					$.ajax({
						url:"<?php echo $url_product;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							alert(data);
							item_qty = $.parseJSON(data);		
							$("#current_qty"+index).val(item_qty.qty);
						},
						error:function(e){
							//alert(e);
						}
				});
			
}
$( document ).ready(function() {
<?php if($this->rsq['is_approved']!=1){?>
	//getsaleOrderNumber();
<?php }?>
	//initList();
	//initListTermcondition();
});
function initList() {
	index5=0;
	var template;
	var option5 = '<?php echo $this->items;?>';
	<?php if(!empty($this->rs)) {
		foreach($this->rs AS $i=>$r){?>
	index5++; 
	index=index+1;
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	if(index5 == 1) {
		template+='<td >&nbsp;</td>';
	} else {
		template+='<td ><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td  width="1%">'+index5+'</td>';
	template+='<td width="30%"><select class="form-control select2me" Onchange="ShowPopupProduct('+ index5 + ');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'<option></option></select>'+inp+'</td>';
	template+='<td><labe id="lb_measure_'+index5+'"></label></td>';
	template+='<td><input style="background:#f5e1e1;" readonly type="text" class="form-control" id="current_qty'+index5+'" name="current_qty'+index5+'" /></td>';
	template+='<td ><input type="text" onkeyup="calculatePrice('+index5+')" class="form-control" required="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
	template+='<td ><div class="input-icon left"><i class="fa">$</i><input style="text-align:right;" type="text" onkeyup="calculatePrice('+index5+')" required="1" readOnly="readOnly" class="validate[required,custom[number]] input form-control" id="price'+index5+'" name="price'+index5+'" /><input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
	template+='<td  width="5%"><input type="text" onkeyup="calculatePrice('+index5+')" readOnly="readOnly" value="0" id="dis_value'+index5+'" name="dis_value'+index5+'" class="form-control" /><input type="hidden" id="olddis_value_'+index5+'" name="olddis_value_'+index5+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
	template+='<td ><div class="input-icon left"><i class="fa">$</i><input style="text-align:right;" type="text" class="form-control" readonly="readonly" id="total'+index5+'" name="total'+index5+'" /></span></td>';
	template+="</tr>";
	$('#table_order').append(template);
	
	$("#item_id_"+index5).val("<?php echo $r['pro_id'];?>");
	$("#qty"+index5).val("<?php echo $r['qty_order'];?>");
	//$("#qty_unit_"+index5).val("<?php echo $r['qty_unit'];?>");
	
	//$("#qty_per_unit_"+index5).val("<?php echo $r['qty_detail'];?>");
	$("#total"+index5).val("<?php echo $r['sub_total'];?>");
	$("#price"+index5).val("<?php echo $r['price'];?>");
	$("#oldprice_"+index5).val("<?php echo $r['price'];?>");
	$("#dis_value"+index5).val("<?php echo $r['benefit_plus'];?>");
	document.getElementById('lb_measure_'+index5).innerHTML = '<?php echo $r['measure'];?>';
	getQtyItemById(index5);
	//getQtyById(index5);
	//getProductPrice(item_id,index5);

	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	
	$("#paid").val(0);
	$("#row_order_0").remove();
		<?php } }?>
}
function initListTermcondition() {
	index1=0;
	term_option = '<?php echo $this->term_opt; ?>';
	<?php if(!empty($this->rsterm)) {
		foreach($this->rsterm AS $i=>$rt){?>
		index1++; 
		template='<tr id="row_term_'+index1+'" style="height:33px;">';
	    template+='<td width="20px" ><img onClick="deleteTermRecord('+index1+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
		template+='<td  width="2%">'+index1+'</td>';
		template+='<td><select class="form-control select2me" id="termid_'+index1+'" name="termid_'+index1+'" >'+term_option+'<option></option></select></td>';
		template+="</tr>";
		$('#table_termcondition').append(template);
		if($('#identity_term').val()!="") {
			var identity = $('#identity_term').val();
			$('#identity_term').val(identity+','+index1);
		} else {$('#identity_term').val(index1);}
		$("#termid_"+index1).val("<?php echo $rt['condition_id'];?>");
		$("#row_term_0").remove();	
	<?php } }?>
}
term_option = '<?php echo $this->term_opt; ?>';
index1 = 0;
function addtermcondition(t_id){
	index1++; 
	template='<tr id="row_term_'+index1+'" style="height:33px;">';
    template+='<td width="20px" ><img onClick="deleteTermRecord('+index1+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	template+='<td  width="2%">'+index1+'</td>';
	template+='<td><select class="form-control select2me" id="termid_'+index1+'" name="termid_'+index1+'" >'+term_option+'<option></option></select></td>';
	template+="</tr>";
	$('#table_termcondition').append(template);
	if($('#identity_term').val()!="") {
		var identity = $('#identity_term').val();
		$('#identity_term').val(identity+','+index1);
	} else {$('#identity_term').val(index1);}
	$("#termid_"+index1).val(t_id);
	$("#row_term_0").remove();	
}
<?php $url_qty =  $this->url(array('module'=>'purchase','controller'=>'purchaserequest','action'=>'getqtybyid')); ?>
function getQtyItemById(index){//use
	
				item_id=$("#item_id_"+index).val();
				//qty_unit=$("#qty_unit_"+index).val();
				//qty_per_unit=$("#qty_per_unit_"+index).val();

				branch_id = $("#branch_id").val();
				if(branch_id=='' || branch_id==-1){alert("Please Select Branch First ");}
				
					$.ajax({
						url:"<?php echo $url_qty;?>",
						type:"post",
						data:{'item_id':item_id,'branch_id':branch_id},
						success: function(data){
							//alert(data);
							item_qty = $.parseJSON(data);		
							$("#current_qty"+index).val(item_qty.qty);
							//main_qty =$("#qty_unit_"+index).val();
							//detail_qty =  $("#qty_per_unit_"+index).val();
							//total_qty = parseFloat(main_qty) + parseFloat(detail_qty/(item_qty.qty_perunit));
							//$("#qty"+index).val(total_qty.toFixed(3));
							//calculatePrice(index);
							//getProductPrice(item_id,index);
						},
						error:function(e){
							//alert(e);
						}
				});
			
}

<?php $url_price =  $this->url(array('module'=>'purchase','controller'=>'purchaserequest','action'=>'getproductprice')); ?>
function getProductPrice(product_id,recordid){
	customer_id=$("#customer_id").val();
	if(customer_id==null || customer_id=="" || customer_id==-1){
		alert("Please Select Customer First !");
		return fale;
		$("#customer_id").focus();
	}else{
		$.ajax({
			url:"<?php echo $url_price;?>",
			type:"post",
			data:{'customer_id':customer_id,'product_id':product_id},
			success: function(data){
				data = $.parseJSON(data);			
				$("#price"+recordid).val(data.price);
				$("#oldprice_"+recordid).val(data.price);
				calculatePrice(recordid);
			},
			error:function(e){
				//alert(e);
			}
	});
  }
}

function getItemOrder(){
	item_ids=$("#add_item").val();
	branch_id = $("#branch_id").val();
	$('#add_item').val('').trigger("liszt:updated");
	if(item_ids==-1){
		return false;
	}
	customer_id=$("#customer_id").val();
	if(customer_id==null || customer_id=="" || customer_id==-1){
			alert("Please Select Customer First !");
			return fale;
	}else{
		addRow(item_ids);
	}
	$("#add_item").val("");
}
function getTermItem(){
	termid=$("#term_item").val();
	$('#term_item').val('').trigger("liszt:updated");
	if(termid==-1){
		return false;
	}
	addtermcondition(termid);
	$("#term_item").val("");
}
var record_index= 1;
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function deleteTermRecord(termid){
	var identity = $('#identity_term').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == termid) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity_term').val(strings);
	$("#row_term_"+termid).remove();
}
function netTotal() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = ($('#dis_value').val());
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun").val();
				totalpayment = alltotal - discountValue;
				$('#all_total').val(totalpayment);
		}
	}else{
		alltotal = $("#totalAmoun").val();
		totalpayment = alltotal - 0;
		$('#all_total').val(totalpayment);
	}
}
function CalcualteTax() {
	$('#status').val();
}
function totalQty(index){
	getQtyById(index);
}
function calculatePrice(index) {
	var qty = $('#qty'+index).val();
	var price = $('#price'+index).val();
	var total = price * qty;
	//alert("total then aftet discount"+total);
	var ds = $('#dis_value'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total + parseFloat(discount);
				
			}else{
				after_discount = total + parseFloat(discount);
			}
			$('#total'+index).val(after_discount.toFixed(2));
		}else{
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total + parseFloat(discount);
			}else{
				discount=$('#dis_value'+index).val(0);
				after_discount = total;
			}
			$('#total'+index).val(parseFloat(after_discount).toFixed(2));
		}
		
	}else{
		$('#total'+index).val(parseFloat(total).toFixed(2));
	}
	netTotal();
}
 var record_id = 1;
function ShowPopupProduct(recordid){
	//alert(recordid+"ddddd");
	item_id = $("#item_id_"+ recordid).val();
	record_id = recordid;
	if(item_id==-1){
		$('#productpopup').modal('show');
	}
	else{
		getQtyById(recordid);
		//getProductPrice(item_id,recordid);
	}
}
function getCustomerInfo(){
	v_id = $("#customer_id").val();
	if(v_id==-1){
		$('#dialogvendor').modal('show');
	}
}
<?php $url_add_vendor =  $this->url(array('module'=>'purchase','controller'=>'vendor','action'=>'add-vendor')); ?>
function addNewVendor(){
	var v_name  = $("#vendor_name").val();
	var contact = $("#txt_contact_name").val();
	var phone   = $("#v_phone").val();
	var address = $("#txt_address").val();
	var txt_mail= $("#txt_mail").val();
	validate_text('#vendor_name');
	$.ajax({
        url: "<?php echo $url_add_vendor;?>",
        type: "post",
        data: {'v_name':v_name,'contact':contact,'phone':phone,'address':address,'txt_mail':txt_mail},
        success: function(data){
            val = $.parseJSON(data);
	        $('#v_name').append($("<option></option>").attr("value",val['vid']).attr("selected",true).text(v_name));  
            $("#contact").val(contact);
            $("#txt_phone").val(phone);   
            $("#vendor_address").val(address);     
            document.getElementById("frmvendor").reset();
            HideDialogVendor();
        },
        error:function(){
            alert("faile insert");
            $("#result").html('There is error while submit');
        }
    });
}
function filterBranch(){
	var location_id= $("#branch_id").val();
	if(location_id==-1){
		    // AddNewLocation(true);
	  }	else{
		  getQuotenumber();
		  getsaleOrderNumber();
		  }
}
<?php $url_code =  $this->url(array('module'=>'sales','controller'=>'quoatation','action'=>'getquoteno')); ?>
function getQuotenumber(){
	$("#txt_order").val("");
				branch_id=$("#branch_id").val();
				if(branch_id=="" || branch_id ==null || branch_id==-1){
					return false;
				}
				else{
				$.ajax({
						url:"<?php echo $url_code;?>",
						type:"post",
						data:{'branch_id':branch_id},
						success: function(data){
							qo = $.parseJSON(data);
							$("#txt_order").val(qo);
						},
						error:function(){
						}
					});
				}	
}
<?php $url_so =  $this->url(array('module'=>'sales','controller'=>'index','action'=>'getsonumber')); ?>
function getsaleOrderNumber(){
	           branch_id=$("#branch_id").val();
				if(branch_id=="" || branch_id ==null || branch_id==-1){
					return false;
				}
				else{
				$.ajax({
						url:"<?php echo $url_so;?>",
						type:"post",
						data:{'branch_id':branch_id},
						success: function(data){
							so = $.parseJSON(data);
							$("#so_number").val(so);
						},
						error:function(){
						}
					});
				}	
}
</script>	