<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("SALEDETAIL_REPORT");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("SALEORDER_APPROVED");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style="width:280mm; min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%; font-size:12px !important;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
						<tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
		                	<td width="60%" valign="top">
		                		<ul>
									<li></li>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'">បណ្ណ័ស្នើរសុំបើកសម្ភារៈពីឃ្លាំង</li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top" >
		                		<table width="100%" cellpadding="0" cellspacing="0" style="font-size:12px !important;">
									<tr>
										<td colspan="2" style="width:100%">
											<table width="100%" cellpadding="0" cellspacing="0">
												<tr>
													<td style="font-size:12px !important;"><div >
														<label  style="float:left; white-space:nowrap; padding-right: 18px;" ><input <?php if($this->product[0]['re_type']==1){echo 'checked="cheched"';} ?> type="checkbox" name="" style="float:left !important;"/>E</label>
														<label style="float:left; white-space:nowrap; padding-right: 18px;"><input <?php if($this->product[0]['re_type']==2){echo 'checked="cheched"';}?> type="checkbox" name="" style="float:left !important;"/>W</label>
														<label  style="float:left; white-space:nowrap; padding-right: 18px;"><input <?php if($this->product[0]['re_type']==3){echo 'checked="cheched"';}?> type="checkbox" name="" style="float:left !important;"/>G</label>
														<label style="float:left; white-space:nowrap; padding-right: 18px;"><input  <?php if($this->product[0]['re_type']==4){echo 'checked="cheched"';}?> type="checkbox" name="" style="float:left !important;"/>M</label>
														<label style="float:left; white-space:nowrap; padding-right: 18px;"><input  <?php if($this->product[0]['re_type']==5){echo 'checked="cheched"';}?> type="checkbox" name="" style="float:left !important;"/>P</label>
														<label style="float:left; white-space:nowrap; padding-right: 18px;"><input  <?php if($this->product[0]['re_type']==6){echo 'checked="cheched"';}?> type="checkbox" name="" style="float:left !important;"/>S</label>
														<label style="float:left; white-space:nowrap; padding-right: 18px;"><input  <?php if($this->product[0]['re_type']==7){echo 'checked="cheched"';}?> type="checkbox" name="" style="float:left !important;"/>MT</label>
														<label style="float:left; white-space:nowrap; padding-right: 18px;"><input  <?php if($this->product[0]['re_type']==8){echo 'checked="cheched"';}?>type="checkbox" name="" style="float:left !important;"/>K</label>
														<label  style="float:left; white-space:nowrap; padding-right: 18px;"><input  <?php if($this->product[0]['re_type']==9){echo 'checked="cheched"';}?> type="checkbox" name="" style="float:left !important;"/>OT................................................ថ្ងៃទី :   .............<?php echo $this->product[0]['date_sold'];?>............</label>
														
													</div></td>
													
												</tr>
											</table>
										</td>
									</tr>
		                			<tr>
										<td style="width:50%">
											<table style="border-collapse:collapse; font-size:10px;" width="100%" cellspacing="0">
												<tr>
													<td>
														<strong>ស្នើដោយ : </strong>
													</td>
													<td style="border-bottom:1px dotted #000; width:80%;">
														<?php echo $this->product[0]['request_name'];?>
													</td>
												</tr>
											</table>
										</td>
										<td style="width:50%">
											<table style="border-collapse:collapse; font-size:10px;" width="100%" cellspacing="0">
												<tr>
													<td>
														<strong>តំណែង : </strong>
													</td>
													<td style="border-bottom:1px dotted #000; width:80%;">
														<?php echo $this->product[0]['position'];?>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										
										<td style="width:50%">
											<table style="border-collapse:collapse; font-size:10px;" width="100%" cellspacing="0">
												<tr>
													<td>
														<strong>គម្រោង : </strong>
													</td>
													<td style="border-bottom:1px dotted #000; width:80%;">
														<?php echo $this->product[0]['plant'];?>
													</td>
												</tr>
											</table>
											
										</td>
										<td style="width:50%">
											<table style="border-collapse:collapse; font-size:10px;" width="100%" cellspacing="0">
												<tr>
													<td>
														<strong>ទីតាំង : </strong>
													</td>
													<td style="border-bottom:1px dotted #000; width:80%;">
														<?php echo $this->product[0]['position'];?>
													</td>
												</tr>
											</table>
										</td>
								​	</tr>
				                </table>
				              </td>
				           </tr> 
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel"><br />
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
		                 <tbody>
		                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?></td>
							<td><?php echo $tr->translate("ITEM_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("QTY");?></td>
							<td width="5%"> <?php echo $tr->translate("MEASURE");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("ITEM_PRICE");?></td>
							<td><?php echo $tr->translate("NOTE");?></td>
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["qty_order"],2);?></td>
						   <td>&nbsp;<?php echo $rs["measure"];?></td>
						   <td>&nbsp;<?php echo $rs["curr_name"]."&nbsp;";echo number_format($rs["price"],2);?></td>
						   <td>&nbsp;<?php echo $rs["remark"];?></td>
						</tr>
						   <?php 
                    }?>
                   
		            </tbody>
		           </table>
		              
		    		</td>
		    	</tr>
			</tbody>
		</table>
		<br>
			<form method="post" >
		            <table align="center" width="100%" >
						<tbody>
						   <tr style="font-size: 11px;">
							 <td><textarea name="remark" class="form-control" placeholder="Remark Here"></textarea></td>
							 <td width="10%"><input type="hidden" name="branch_id" value="<?php echo $this->product[0]['branch_id']; ?>" /></td>
						      <td>
								<select class="form-control" name="apprrove">
									<option value="1">Approved</option>
									<option value="1">Reject</option>
								</select>
							  </td>
						   </tr>
						</tbody>
					</table><br />
					<div class="form-group">
							
							<label  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/sales/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>
												
							</label>
						</div>
			</form>
			
		</div>
		
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
