<?php 					
	$url_new = $this->url(array('module'=>'billing','controller'=>'truck','action'=>'add',),null,true);
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	//print_r($this->rs);
?>
<title><?php echo $tr->translate("MENU_PURCHASE_ADVANCE_INDEX");?></title>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("LIST_TRUCK");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
			</div>
			<div class="portlet-body form frmfilter">
				<form method="post" action="">
				    <label class="col-md-4 control-label"><?php echo $formFilter->getElement('search_name');?></label> 
				    <label class="col-md-4 control-label"><?php echo $formFilter->getElement('status_serach');?></label> 
				    <label class="col-md-2control-label"> <button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button> </label> 
				</form> 
				<div class="contain_form" style="clear: both;">
					<table class="collape tablesorter" id="exportExcel" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NUM");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TRUCT_CAT_NAME_EN");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TRUCT_CAT_NAME_EN");?></th>
								<th class="tdheader"><?php echo  $tr->translate("DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
								<th class="tdheader"><?php echo  $tr->translate("STATUS");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "exportExcel";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
									
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'")});
											$("input:.pagedisplay").focus(function(){ this.blur(); });
									
											function changeColor(){
												alert("change color on mouse over");
											}
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($this->rs)){
								foreach ($this->rs as $key=>$rs){
									$status='';
									if($rs["status"]==5){$status ="style='pointer-events: none;cursor: default;color: #ccc;'";}
									if($rs['status']==1){
										$staus="<img src=".$this->baseUrl().'/images/icon/apply2.png'." >";
									}else{
										$staus="<img src=".$this->baseUrl().'/images/icon/delete-row.png'." >";
									}
							?>
								<tr class="normal">
									<td class="items-no"><?php echo $key+1;?></td>
									<td class="items"><a href="<?php echo $this->baseUrl();?>/billing/youdriver/edit/id/<?php echo $rs["id"]?>"><?php echo $rs["name_kh"];?></a></td>
									<td class="items"><a href="<?php echo $this->baseUrl();?>/billing/youdriver/edit/id/<?php echo $rs["id"]?>"><?php echo $rs["name_en"];?></a></td>
									<td class="items"><a href="<?php echo $this->baseUrl();?>/billing/youdriver/edit/id/<?php echo $rs["id"]?>"><?php echo $rs["date"];?></a></td>
									<td class="items-no" style="white-space: nowrap;">
										<a <?php echo $status; ?> href="<?php echo $this->baseUrl();?>/billing/youdriver/edit/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("EDIT");?></a> | 
									</td>
									<td class="items"><?php echo $staus;?></td>
								</tr>
							<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table><?php echo $footer?>
						<?php echo $this->list; ?>
			    </div>
		   </div>
		</div>
	</div>
</div>