<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'sales','controller'=>'staff','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'sales','controller'=>'staff','action'=>'index'));
	$url_new = $this->url(array('module'=>'sales','controller'=>'quoatation','action'=>'edit'));
	//print_r($this->qqq);
?>
<title><?php echo $tr->translate("STAFF");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("STAFF")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="form_sample_2" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2">
								<?php echo $tr->translate("NAME");?>
							<span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("name");?>
									<?php echo $form->getElement("id");?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("POSITION");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("position");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PHONE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement('phone');?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php  echo $tr->translate("EMAIL");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("email");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("STATUS");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									
									<?php echo $form->getElement("status");?>
								</div>
							</div>
						</div>
						<!-- blog bottom -->
						<div class="form-group">
							<div  class="col-md-8 col-md-offset-4 col-md-4">
								<a href="<?php echo $url_cancel; ?>"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<!--<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>-->
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>