<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("PRINT_PARTY_CASH_REQUEST");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PRINT_PARTY_CASH_REQUEST");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<!--<li>
										<a href="javascript:;"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>-->
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%; margin-top:10px;" >
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
		th{padding: 0px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
		.background{background: #ccc !important;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
							<tr>
								<td width="20%" valign="middle"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:14px; margin-top:25px; font-family:'Khmer OS Muol Light';white-space: nowrap;"><?php echo $tr->translate('REQUEST_CASH_BUY_PRODUCT'); ?></li>
									</ul>
								</td>
								<td width="20%"></td>
							</tr> 
							
							<tr>
								<td width="20%" valign="top">
									<table width="100%" style="font-size: 12px; !important ;margin-bottom: 5px;" border="1">
										<tr>
											<td style="text-align: left; white-space:nowrap; border-right:1px solid #fff;">&nbsp;<?php echo $tr->translate("PLAN");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;min-width: 150px;" class='background'><?php echo $this->product[0]['plan'];?></td>
										</tr>
										<tr>
											<td style="text-align: left; white-space:nowrap;border-right:1px solid #fff;">&nbsp;<?php echo $tr->translate("NUMBER_REQUEST");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;" class='background'><?php echo $this->product[0]['number_request'];?></td>
										</tr>
										<tr>
											<td style="text-align: left;white-space:nowrap;border-right:1px solid #fff;">&nbsp;<?php echo $tr->translate("DATE_REQUEST_WORK_SPACE");?> </td>
											<td style="text-align: right; white-space:nowrap;">:</td>
											<td style="text-align: right;white-space:nowrap;" class='background' ><?php echo date("d/m/Y",strtotime($this->product[0]['date_from_work_space']));?></td>
										</tr>
									</table>
								</td>
								<td width="60%" valign="top">
								</td>
								<td width="20%" style="text-align: right;font-size: 12px;">
									<table width="100%" style="font-size: 12px; !important" border="1" cellspacing="5" cellpadding="5">
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("BRANCH_NAME");?> :</td>
											<td style="text-align: right;white-space:nowrap; min-width: 150px;" class='background'><?php echo $this->product[0]['branch'];?></td>
										</tr>
										<tr>
											<td style="text-align: right; white-space:nowrap;"><?php echo $tr->translate("REQUEST_NO");?> :</td>
											<td style="text-align: right;white-space:nowrap;" class='background'><?php echo $this->product[0]['re_code'];?></td>
										</tr>
										<tr>
											<td style="text-align: right;white-space:nowrap;"><?php echo $tr->translate("REQUEST_DATE");?> :</td>
											<td style="text-align: right;white-space:nowrap;" class='background'><?php echo date("d/m/Y",strtotime($this->product[0]['date_request']));?></td>
										</tr>
									</table>
									<!--<ul class='pur_info'>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("BRANCH_NAME");?> : </strong><?php echo $this->product[0]['branch'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_NO");?> : </strong><?php echo $this->product[0]['re_code'];?></li>
			                					<li style="text-align: right;"><strong><?php echo $tr->translate("REQUEST_DATE");?> : </strong><?php echo date("d/m/Y",strtotime($this->product[0]['date_request']));?></li>
												<li style="text-align: left;"><strong><?php echo $tr->translate("PEDDING");?> : </strong><?php echo $this->product[0]['pedding'];?></li>
		                						<li style="text-align: left;"><strong><?php echo $tr->translate("PURCHASE_STATUS");?> : </strong><?php echo $this->product[0]['status'];?></li>
		                			</ul>-->
								</td>
							</tr> 							
		                 
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
						 <tr bgcolor="#ccc" class="style" align="center" style="background:#ccc !important;font-weight:800 !important; line-height: 30px; font-size:14px !important; padding:1px 0px; white-space: nowrap; ">
		                    <th width="5%"><?php echo $tr->translate("NUM");?></th>
							<th width="15%"><?php echo $tr->translate("ACCESSORY_CODE");?></th>
							<th width="15%"><?php echo $tr->translate("ITEM_NAME");?></th>
							<!--<th width="10%"><?php echo $tr->translate("TYPE");?></th>
							<th width="5%"><?php //echo $tr->translate("SIZE");?></th>
							<th width="5%"><?php //echo $tr->translate("LENGHT");?></th>-->
							<th width="5%"><?php echo $tr->translate("MEASURE");?></th>
							<th width="10%"><?php echo $tr->translate("TOTAL_QTY");?></th>
							<th width="5%"><?php echo $tr->translate("UNIT_PRICE");?></th>
							<th width="10%"><?php echo $tr->translate("TOTAL");?></th>
							<th width="10%"><?php echo $tr->translate("REQ_DATE_IN");?></th>
							<th width="25%"><?php echo $tr->translate("WORK_REMARK");?></th>
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
						$count = count($this->product);
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){?>
							<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						    <td style="white-space: nowrap;" align="center">&nbsp;<?php echo $rs["measure"];?></td>
						   <td style="white-space: nowrap !important;">&nbsp;<?php echo number_format($rs["qty"],2);?></td>
						   <td style="white-space: nowrap !important;">&nbsp;$&nbsp;<?php echo number_format($rs["price"],2);?></td>
						   <td style="white-space: nowrap !important;">&nbsp;$&nbsp;<?php echo number_format($rs['total'],2);?></td>
						   <td style="white-space: nowrap !important;" align="center">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_in"]));?></td>
						   <td style="white-space: nowrap !important;">&nbsp;<?php echo $rs["remark"];?></td>
						</tr>
						   <?php 
						   $d_netotal = $d_netotal+$rs['total'];
                    }?>
					<?php 
						$length = 8 - $count;
						if($length>0){
							for($i=1;$i<=$length;$i++){ $no = $count+$i;
					?>
						<tr class='row-format<?php //echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center">&nbsp;<?php echo $no?></td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						</tr>
					<?php 
							}
						}
					?>
                    <tr class='row-format<?php //echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td style="white-space: nowrap;" colspan="6px" align="right">&nbsp;<?php echo $tr->translate("TOTAL_AMOUNT");?>&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;$&nbsp;<?php echo number_format($d_netotal,2);?></td>
						   <td style="white-space: nowrap;border-bottom: 1px solid #fff;border-right: 1px solid #fff;" colspan="2" >&nbsp;</td>
						</tr>
		                </tbody>
		           </table>
		              <table align="center" width="100%" >
						   <tbody>
						   <tr>
							<td colspan="7">
								<table style="font-size:12px; width:100%">
									<tr>
										<td style="width:2%">បញ្ជាក់ៈ </td>
										<td style="border-bottom:1px dotted #000;"><?php echo $this->product[0]["p_remark"]?></td>
									</tr>
									<tr>
										<td colspan="2"> សូមលោកប្រធានផ្នែកផ្គត់ផ្គង់ផ្តល់ពត៌មាន  នូវរយៈពេលដែលសម្ភារៈមកដល់ក្រុមហ៊ុន ឬ អ្នកស្នើសម្ភារៈ។</td>
									</tr>
								</table>
							</td>
						   </tr>
						   <tr style="font-size: 12px;">
						        <td style="width:25%;text-align:center; font-family:'Khmer OS Muol Light'">អនុម័ត<br />អគ្គនាយ&nbsp;/&nbsp;អគ្គនាយករង</td>
						         <td></td>
						        <td style="width:25%;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("ពិនិត្យទទួលស្គាល់");?><br /><?php echo $tr->translate("ផ្នែករដ្ឋបាល");?></td>
						        <td></td>
						        <td style="width:25%;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("CHECKAND_APROVE");?><br /><?php echo $tr->translate("BUYER_MANAGER");?></td>
						        <td></td>
						        <td style="width:25%;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("REQUEST_BY");?><br /><?php echo $tr->translate("PURCHASING");?></td>
						   </tr>
						    <tr style="font-size: 12px; height: 75px;">
						        <td valign="bottom" style="width:15%;text-align:center;  font-family:'Khmer OS Muol Light'; white-space: nowrap; border-bottom:1px solid #000;"></td>
						        <td style="width:2%;";></td>
						        <td valign="bottom" style="width:15%;text-align:center;  font-family:'Khmer OS Muol Light'; white-space: nowrap; border-bottom:1px solid #000;"></td>
						        <td style="width:2%;"></td>
						        <td valign="bottom" style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td style="width:1%;"></td>
						        <td valign="bottom" style="width:30%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						   </tr>
						   <tr>
								<td style="text-align:center;font-family:'Khmer OS Muol Light';"></td>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
    var printContents = document.getElementById('divPrint').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
}
</script>
