<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_cancel =  $this->url(array('module'=>'product','controller'=>'adjust','action'=>'index'));
	$url_getProduct =  $this->url(array('module'=>'','controller'=>'ajax','action'=>'get-product-name'));
	$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("ADJUST_STOCK");?></title>
<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-globe"></i><?php echo $tr->translate("ADJUST_STOCK");?>
			</div>
				<a href="<?php echo $url_cancel;?>" class="pull-right"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" id="frm" method="post" autocomplete="off" >
				<div class="form-body">	
							<div class="form-group">
								<label  class="col-md-12">
								<input type="hidden" class="form-control" id="add_item" name="add_item" Onchange="addNew();" style="width:100%;" placeholder="<?php echo $tr->translate("SELECT_PRODUCT");?>"/>
								</label>
							</div>
								<div class="table-responsive">
									<table class="table table-bordered">
										<thead>
											<tr>
												<th><?php echo $tr->translate("NUM");?></th>
												<th><?php echo $tr->translate("PRODUCT_NAME");?></th>
												<th><?php echo $tr->translate("CURRENT_QTY");?></th>
												<th><?php echo $tr->translate("NEW_QTY");?></th>
												<th><?php echo $tr->translate("DIFFERENCE_QTY");?></th>
												<th><?php echo $tr->translate("REMARK");?></th>
												<th><?php echo $tr->translate("ACTION");?></th>
											</tr>
										</thead>
										<tbody id="tr_location" style="font-size:12px;">
										</tbody>
									</table>
								</div>
								<input type="hidden" name="identity" id="identity" value="<?php //echo $identity;?>" >
							<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
									<a href="<?php echo $this->baseUrl();?>/product/adjust"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
									<button type="submit" name="saveclose" id="saveandclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
									<button type="submit" name="btnsavenew" id="save_close" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
									
								</label>
							</div>
				</div>
			</form>
		</div>
</div>
<script type="text/javascript">
$('#frm').submit(function() {
	identity =$("#identity").val();
	if(identity=='' || identity==-1){
		alert("ទិន្នន័យមិនអាចរក្សាទុកបានទេ ។សូមត្រួតពិនិត្យមើលម្តងទៀត");
		$('#add_item').select2('open');
		return false;
	}
	var r = confirm("\tសូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\t\n \tតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?\t");
	if (r == true) {
	    return true;
	} else {
	   return false;
	}
});	
itemss = <?php echo Zend_Json::encode($this->product)?>;
$( document ).ready(function() {
	select2Speed('add_item');
});
function select2Speed(name){
	 $('#add_item').select2({
            data : _.map(_.range(0, itemss.length), function (i) {
                  return {
                      id  : itemss[i].id,
                      text: itemss[i].item_code+"-"+itemss[i].item_name
                  };
            }),
            dropdownCssClass : 'capitalize',
            containerCssClass: 'capitalize',
            formatLoadMore   : 'Loading more...',
            query            : function (q) {
            // pageSize is number of results to show in dropdown
                var pageSize,
                    results;
                    pageSize = 20;
                    results  = _.filter(this.data, function (e) {
                        return (q.term === "" || e.text.toUpperCase().indexOf(q.term.toUpperCase()) >= 0);
                 });
                q.callback({
                    results: results.slice((q.page - 1) * pageSize, q.page * pageSize),
                    more   : results.length >= q.page * pageSize
                });
            }
        });
}
var index=0;
function addNew(){
	id = $("#add_item").val();
	index++;
	$.ajax({
        url: "<?php echo $url_getProduct;?>",
        type: "post",
        data: {'item_id':id},
        success: function(data){
        	item = $.parseJSON(data);	
			for(i=1; i<index; i++){
				new_item=parseInt(id);
				items = parseInt($("#pro_id_"+i).val());
				if(new_item==items){		
					newqty = parseInt($("#new_qty_"+i).val());
					newqty = newqty+1;
					$("#new_qty_"+i).val(newqty);
					diferQTY(i);
					return false;
				}
			}
			template='<tr id="row_location_'+index+'">';
			template+='<td>'+index+'</td>';
			template+='<td style="white-space: nowrap;">'+item.item_name+'<input type="hidden" id="pro_id_'+index+'" name="pro_id_'+index+'" value="'+item.id+'" </td>';
			template+='<td><input type="text" id="current_qty_'+index+'" onKeyup="diferQTY('+index+')" name="current_qty_'+index+'" value="'+item.qty+'" class="form-control"></td>'; 
			template+='<td><input type="text" id="new_qty_'+index+'" name="new_qty_'+index+'" onKeyup="diferQTY('+index+')" value="0" class="form-control"></td>'; 
			template+='<td><input type="text" id="difer_qty_'+index+'" name="difer_qty_'+index+'" class="form-control"></td>';
			template+='<td><input type="text" id="remark_'+index+'" name="remark_'+index+'" class="form-control"></td>';
			template+='<td><button type="button" onClick="deleteRecord('+index+',1)" name="save_close" class="btn default"><?php echo $tr->translate("DELETE");?></button></td>';
			template+='</tr>';
			$('#tr_location').append(template);
			if($('#identity').val()!="") {
				var identity = $('#identity').val();
				$('#identity').val(identity+','+index);
			} else {$('#identity').val(index);}
			diferQTY(index);
        },
        error:function(){
           alert("error");
        }
    });
}
	function diferQTY(index){
		cur_qty = $('#current_qty_'+index).val();
		new_qty = $('#new_qty_'+index).val();
		difer_qty = parseFloat(new_qty)-parseFloat(cur_qty);
		$('#difer_qty_'+index).val(difer_qty);
	}
function deleteRecord(index,type) {
		if(type==1){
			var identity = $('#identity').val();
			var arrays = identity.split(',');
		}else{
			var identity = $('#identity_price').val();
			var arrays = identity.split(',');
		}
		
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		
		if(type==1){
			$('#identity').val(strings);
			$("#row_location_"+index).remove();
		}else{
			$('#identity_price').val(strings);
			$("#row_price_"+index).remove();
		}
	}
</script>