<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>

<title><?php echo $tr->translate("USERACCESS")?></title>
<?php $url = $this->baseUrl()."/rsvacl/useraccess/view-user-access?id="; ?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("USERACCESS");?>
				</div>
			
			</div>
			<div class="portlet-body form">
			<?php echo $this->list; ?>
			</div>
		</div>
	</div>
</div>