<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("MAKE_INVOCIE");?></title>
<div class="row">
<!--<marquee style="margin-top:-20px;" behavior="scroll" direction="left" onmouseout="this.start()" onmouseover="this.stop()" scrollamount="5">យើងត្រូវការ ការយល់ព្រមពី ផ្នែកគណនេយ្យ /ហិរញ្ញវត្ថុ ឫអ្នកដែលមានសិទ្ធ ដើម្បី <span style="color:red;">បង្កើតជាវិក័យបត្រ និង របាយការណ៏ប្រគល់ទំនិញ</span> / We need approval from  or person who have permission to <span style="color:red;">issue invoice and Delivery Report</span> ! </marquee>-->
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("DELIVERY_NOTE");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	 <?php $url_submit = $this->url(array('module'=>'sales','controller'=>'delivery','action'=>'adddelivery'));?>
	<form id="form_sample_2" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">		   
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
						<tr style="margin-bottom:10px;"> 
								<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:20px; margin-top:25px; font-family:'Khmer OS Muol Light';">ប័ណ្ណបញ្ជាលក់ទំនិញ</li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
									<!--<div  style=" border:1px solid #000; border-radius:5px !important;line-height: 11px;padding: 5px 5px">
										<p>ក្រុមហ៊ុន កាណាខនគ្រីត </p><p>ផ្នែកបញ្ជាទិញ និងគ្រប់គ្រងតម្លៃ</p>
									</div>-->
								</td>
							</tr>
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 11px;">
		                				</td>
		                				<td ></td>
		                				<td width="65%"></td>
		                			</tr>
		                			<tr>
		                				<td style="font-size: 11px;" valign="top" width="35%;"><input type="hidden" name="quote_id" value="<?php echo $this->product[0]['quote_id'];?>" />
		                				<div style="width:100%; background: #244456;display: block;color:#fff;">&nbsp;&nbsp;<?php echo $tr->translate("CUSTOMER_INFO");?></div>
		                				   <table width="100%" style="font-size: 12px; font-weight:600;line-height:25px;">
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("COMPANY_NAME");?> </td>
													<td>:</td>
													<td style="text-align: left;white-space: nowrap;"> <?php echo $this->product[0]['customer_name'];?></td>
												</tr>
												
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("CONTACT_NAME");?> </td>
													<td>:</td>
													<td style="text-align: left;white-space: nowrap;"> <?php echo $this->product[0]['contact_name'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("POSITION");?> </td>
													<td>:</td>
													<td style="text-align: left;white-space: nowrap;"> <?php //echo $this->product[0]['contact_name'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("PHONE");?> </td>
													<td>:</td>
													<td style="text-align: left;white-space: nowrap;"> <?php echo $this->product[0]['phone'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("EMAIL");?> </td>
													<td>:</td>
													<td style="text-align: left;white-space: nowrap;"> <?php echo $this->product[0]['email'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("ADDRESS");?> </td>
													<td>:</td>
													<td style="text-align: left;white-space: nowrap;"> <?php echo $this->product[0]['add_name'];?></td>
												</tr>
											</table>
		                				</td>
		                				<td width="30%"></td>
		                				<td width="35%" style="text-align: left;font-size: 11px;" valign="top">
		                					<div style="padding-left: 10px;width:100%; background: #244456;display: block;color:#fff;"><?php echo $tr->translate("DELIVER_INFO");?></div>
		                					<table width="100%" style="font-size: 12px; font-weight:600; line-height:25px;">
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("SALE_NO");?> </td>
													<td>:</td>
													<td style="text-align: right;white-space: nowrap;"><?php echo $this->product[0]['sale_no'];?></td>
												</tr>
												
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("SALE_DATE");?> </td>
													<td>:</td>
													<td style="text-align: right;white-space: nowrap;"> <?php echo date("d-M-Y",strtotime($this->product[0]['date_sold']));?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("QUOTATION_NO");?> </td>
													<td>:</td>
													<td style="text-align:right;white-space: nowrap;"><?php echo $this->product[0]['quote_no'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("DATE_QUOTE");?> </td>
													<td>:</td>
													<td style="text-align: right;white-space: nowrap;"><?php echo date("d-M-Y",strtotime($this->product[0]['quote_date']));?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("BRANCH");?> </td>
													<td>:</td>
													<td style="text-align: right;white-space: nowrap;"> <?php echo $this->product[0]['branch_name'];?></td>
												</tr>
											</table>
		                				</td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table  style="border-collapse:collapse;border:1px solid #000; font-size:13px;" width="100%" cellspacing="0" border="1">
		                 <tbody>
		                 
		                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 30px; font-size:13px !important; padding:1px 0px; white-space: nowrap; ">
		                    <th width="5%">&nbsp;<?php echo $tr->translate("NUM");?></th>
							<th width="15%">&nbsp;<?php echo $tr->translate("ITEM_CODE");?></th>
							<th width="30%"><?php echo $tr->translate("PRODUCT_DISCRIPTION");?></th>
							<!--<th>&nbsp;<?php echo $tr->translate("MODEL");?></th>
							<th width="10%">&nbsp;<?php echo $tr->translate("PRODUCT_FROM");?></th>-->
							<th>&nbsp;<?php echo $tr->translate("QTY");?></th>
							<th width="5%">&nbsp;<?php echo $tr->translate("MEASURE");?></th>
							<th>&nbsp;<?php echo $tr->translate("REMARK");?></th>
							<!--<td width="10%">&nbsp;<?php //echo $tr->translate("OLD_PRICE");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("COST_PRICE");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("BENEFIT_PLUS");?></td>
							<td><?php echo $tr->translate("TOTAL_SALE_PRICE");?></td>-->
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <!--<td style="white-space: nowrap;">&nbsp;<?php echo $rs["model_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php //echo $rs["serial_number"];?></td>-->
						   <td style="width:10%;text-align:center;font-weight:800;white-space: nowrap;">&nbsp;<?php echo number_format($rs["qty_order"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["measure"];?></td>
						    <td style="white-space: nowrap;">&nbsp;<?php //echo $rs["serial_number"];?></td>
						   <!--<td style="white-space: nowrap;">&nbsp;<?php echo $rs["price"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["benefit_plus"];?></td>-->
						</tr>
						   <?php 
                    }?>
                    
					<!--<tr>
						<td colspan="5" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #fff;">
						<strong  style="font-size: 13px;"><u>សំគាល់ / Remark</u></strong>
							<style>
								ul.termcodition li{ line-height: 20px;list-style-type: none; font-size: 12px;}
							</style>
							
						</td>
					</tr>-->
		            </tbody>
		           </table>
		              <br>
		            
					
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div><!-- end print -->
		 
		<div class="form-group">
			<div  class="col-md-12 col-md-offset-4 col-md-8">
				<a href="<?php echo $this->baseUrl();?>/sales/delivery/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
				<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<!--<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>-->
			</div>
		</div>
		
		</form>	
		
		
		
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>

$(document).ready(function() { 
   
  calculateBalance();
 }); 

 
function calculateBalance(){
	deposit= $("#deposit").val();
	net_total = $('#net_total').val();
	balance = net_total-deposit;
	if(balance<0){
		balance=0;
		$("#deposit").val(net_total);
	}
	$("#balance").val(balance);
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
