<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$form = $this->form;
//print_r($this->product);
?>
<title><?php echo $tr->translate("DELIVERY_NOTE");?></title>
<div class="row">
<!--<marquee style="margin-top:-20px;" behavior="scroll" direction="left" onmouseout="this.start()" onmouseover="this.stop()" scrollamount="5">យើងត្រូវការ ការយល់ព្រមពី ផ្នែកគណនេយ្យ /ហិរញ្ញវត្ថុ ឫអ្នកដែលមានសិទ្ធ ដើម្បី <span style="color:red;">បង្កើតជាវិក័យបត្រ និង របាយការណ៍ប្រគល់ទំនិញ</span> / We need approval from  or person who have permission to <span style="color:red;">issue invoice and Delivery Report</span> ! </marquee>-->
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("DELIVERY_NOTE");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
								</ul>
					</div>
			</div>
    <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:25cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	 <?php $url_submit = $this->url(array('module'=>'sales','controller'=>'delivery','action'=>'adddelivery'));?>
	<form id="form_sample_2" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">		   
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
						<tr style="margin-bottom:10px;"> 
								<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:20px; margin-top:25px; font-family:'Khmer OS Muol Light';">ប័ណ្ណប្រគល់ទំនិញ</li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
									<!--<div  style=" border:1px solid #000; border-radius:5px !important;line-height: 11px;padding: 5px 5px">
										<p>ក្រុមហ៊ុន កាណាខនគ្រីត </p><p>ផ្នែកបញ្ជាទិញ និងគ្រប់គ្រងតម្លៃ</p>
									</div>-->
								</td>
							</tr>
		                <tr>
		                	<td colspan="3" valign="top"><br />
		                		<table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 11px;" valign="top" width="35%;"><input type="hidden" name="quote_id" value="<?php echo $this->product[0]['quote_id'];?>" />
		                				    <div class="form-group">
												<label class="control-label col-md-2">
													<?php //echo $tr->translate("DN_NO");?>
												</label>
												<div class="col-md-4">
													<div class="input-icon right col-md-8">
														<?php //echo $form->getElement("dn_no");?>
													</div>
													
													
												</div>
												
												<label class="control-label col-md-2"><?php echo $tr->translate("MAKE_INVOICE");?>
												</label>
												<div class="col-md-4">
													<div class="col-md-2" style="margin-top:7px"><input type="checkbox" value="1" onClick="makeInvice()" name="is_invoice" id="is_invoice" /></div>
													<div class="col-md-10"><!--<input type="text" class="form-control" name="invoice_no" id="invoice_no" />--></div>
												</div>
											</div>
										   <div class="form-group">
												<label class="control-label col-md-2">
													<?php echo $tr->translate("DN_NO");?>
												<span class="required">
													 </span>
												</label>
												<div class="col-md-4">
														<?php echo $form->getElement("dn_no");?>
												</div>
												
												<label class="control-label col-md-2"><?php echo $tr->translate("DN_DATE");?><span class="required">
												</span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
													<i class="fa fa-calendar"></i><?php echo $form->getElement("date_dn");?>
													</div>
												</div>
											</div>
											<div class="form-group">
												<label class="control-label col-md-2"><?php echo $tr->translate("SALE_NO");?><span class="required">
												* </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php echo $form->getElement("so_number"); ?></div>
												</div>
												<label class="control-label col-md-2"><?php echo $tr->translate("DATE_SOLD");?><span class="required">
												* </span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<?php echo $form->getElement("date_sold"); ?></div>
												</div>
											</div>
											<div class="form-group">
												<label class="control-label col-md-2"><?php echo $tr->translate("CUSTOMER_NAME");?> <span class="required">
													</span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<i class="fa"></i>
														<?php echo $form->getElement("customer_id");?>
														<?php echo $form->getElement("id");?>
													</div>
												</div>
												<label class="control-label col-md-2"><?php echo $tr->translate("BRANCH_NAME");?><span class="required">
													</span>
												</label>
												<div class="col-md-4">
													<div class="input-icon right">
														<i class="fa"></i>
														<?php echo $form->getElement('branch_id');?>
													</div>
												</div>
											</div>
		                				</td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            
		              <br>
		            
					
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div><!-- end print -->
		<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("NUM");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_CODE");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("ITEM_NAME");?></th>
									<th><?php echo $tr->translate("QTY_ORDER");?></th>
									<th><?php echo $tr->translate("QTY_REMAIN");?></th>
									<th><?php echo $tr->translate("MEASURE");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("QTY_DELIVER");?></th>
									<th><?php echo $tr->translate("NOTE");?></th>
							</tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
						 <input type="hidden" name="totalAmoun" id="totalAmoun" value="<?php echo $this->product[0]["sub_total"]?>"/>
						 <input type="hidden" name="dis_value" id="dis_value" value="<?php echo $this->product[0]["disc_value"]?>"/>
						 <input type="hidden" name="all_total" id="all_total" value="<?php echo $this->product[0]["net_total"]?>"/>
 		<div class="form-group">
			<div  class="col-md-12 col-md-offset-4 col-md-8">
				<a href="<?php echo $this->baseUrl();?>/sales/delivery/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
				<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
			</div>
		</div>
		
		</form>	
		
		
		
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>

$(document).ready(function() { 
   
  calculateBalance();
  initList();
 }); 
index=0;

function makeInvice(){
	is_invoice = $("#is_invoice");
	if($("#is_invoice").is(':checked')){
		$('#invoice_no').attr("required",true);
	}
}
 function initList() {
	index5=0;
	var template;
	<?php if(!empty($this->product)) {
		foreach($this->product AS $i=>$r){?>
	index5++; 
	//index=index+1;
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	template+='<td  width="1%">'+index5+'</td>';
	template+='<td width="15%"><?php echo $r["item_code"]?> <input type="hidden" name="item_id_'+index5+'" id="item_id_'+index5+'" value="<?php echo $r['pro_id']?>"</td>';
	template+='<td width="20%"><?php echo $r["item_name"]?> </td>';
	template+='<td ><?php echo $r["qty_order"]?><input type="hidden" id="qty_order_'+index5+'" name="qty_order_'+index5+'" value="<?php echo $r["qty_order"]?>" /></td>';
	template+='<td ><?php echo $r["qty_order_after"]?><input type="hidden" id="qty_order_after_'+index5+'" name="qty_order_after_'+index5+'" value="<?php echo $r["qty_order_after"]?>" /></td>';
	template+='<td width="3%"><?php echo $r["measure"]?> </td>';
	template+='<td ><input type="text" onkeyup="calculatePrice('+index5+')" required="required" onkeypress="return isNumberKey(event)"  class="form-control" id="qty_deliver'+index5+'" name="qty_deliver'+index5+'" /><input type="hidden" name="price_'+index5+'" id="price_'+index5+'" value="<?php echo $r["price"]?>" /><input type="hidden" name="benefit_plus_'+index5+'" id="benefit_plus_'+index5+'" value="<?php echo $r["benefit_plus"]?>" /><input type="hidden" name="sub_total_'+index5+'" id="sub_total_'+index5+'" value="<?php echo $r["sub_total"]?>" /> </td>';
	template+='<td ><input type="text" class="form-control" id="note'+index5+'" name="note'+index5+'" /></span></td>';
	template+="</tr>";
	$('#table_order').append(template);
	
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	
	$("#row_order_0").remove();
	calculatePrice(index5);
		<?php } }?>
}
function netTotal() {//use
	var cur_type = $('#currency').val();
	var netTotal=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	var status = $('#status').val();
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#sub_total_'+rowIDArray[n]).val());
	}
	$('#totalAmoun').val(netTotal.toFixed(2));
	calculateDiscount();
}
function calculateDiscount(){//use
	var discountValue = ($('#dis_value').val());
	if(discountValue.length!=0){
		if(discountValue.indexOf("%")!==-1){
			var pds=discountValue.split("%");
			    alltotal = $("#totalAmoun").val();
				var discount=(alltotal*parseFloat(pds[0]))/100;
				totalpayment = alltotal - discount;
				$('#all_total').val(totalpayment);
		}else{
				alltotal = $("#totalAmoun").val();
				totalpayment = alltotal - discountValue;
				$('#all_total').val(totalpayment);
		}
	}else{
		alltotal = $("#totalAmoun").val();
		totalpayment = alltotal - 0;
		$('#all_total').val(totalpayment);
	}
}
function calculatePrice(index) {
	var qty = parseFloat($('#qty_deliver'+index).val());
	var cu_qty = parseFloat($('#qty_order_after_'+index).val());
	var price = $('#price_'+index).val();
	var total = price * qty;
	
	if(qty>cu_qty){
		$('#qty_deliver'+index).val(cu_qty);
	}
	//alert("total then aftet discount"+total);
	var ds = $('#benefit_plus_'+index).val();
	if(ds.length!=0){
		if(ds.indexOf("%")!==-1){//if have %
			var pds=ds.split("%");
			if(!isNaN(pds[0])){
				var discount=(total*parseFloat(pds[0]))/100;
				after_discount = total + parseFloat(discount);
				
			}else{
				after_discount = total + parseFloat(discount);
			}
			$('#sub_total_'+index).val(after_discount.toFixed(2));
		}else{
			after_discount=0;
			if(!isNaN(ds)&&ds!=0){
				discount = parseFloat(ds).toFixed(2);
				after_discount = total + parseFloat(discount);
			}else{
				discount=$('#benefit_plus_'+index).val(0);
				after_discount = total;
			}
			$('#sub_total_'+index).val(parseFloat(after_discount).toFixed(2));
		}
		
	}else{
		$('#sub_total_'+index).val(parseFloat(total).toFixed(2));
	}
	netTotal();
}
function calculateBalance(){
	deposit= $("#deposit").val();
	net_total = $('#net_total').val();
	balance = net_total-deposit;
	if(balance<0){
		balance=0;
		$("#deposit").val(net_total);
	}
	$("#balance").val(balance);
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
