<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("DELIVERY_NOTE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("DELIVERY_NOTE");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;បោះពុម្ភ/Print
										</a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%; margin-top:15px;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
		th{padding: 0px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0" >
		            	<tbody>
						
						<tr style="margin-bottom:10px;"> 
								<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo/<?php echo $this->title_reprot["logo"]?>"></td>
								<td width="60%" valign="top" style="line-height:30px">
									<ul>
										<li style="text-align:center; font-size:20px; font-family:'Khmer OS Muol Light'"><?php echo $this->title_reprot["title_report_kh"]?></li>
										<li style="text-align:center; font-size:18px; font-family:serif,header-font; font-weight:600;"><?php echo $this->title_reprot["title_report_en"]?></li>
										<li style="text-align:center; font-size:20px; margin-top:25px; font-family:'Khmer OS Muol Light';">ប័ណ្ណប្រគល់ទំនិញ</li>
									</ul>
								</td>
								<td width="20%" style="text-align:center; font-size: 11px;white-space: nowrap;">
									<!--<div  style=" border:1px solid #000; border-radius:5px !important;line-height: 11px;padding: 5px 5px">
										<p>ក្រុមហ៊ុន កាណាខនគ្រីត </p><p>ផ្នែកបញ្ជាទិញ និងគ្រប់គ្រងតម្លៃ</p>
									</div>-->
								</td>
						</tr>
						
		                <tr>
		                	<td colspan="3" valign="top"><br />
		                		<table width="100%" cellpadding="0" cellspacing="0" style="margin-top:15px;">
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 15px;" valign="top" width="35%;">
											<div style="width:100%; background: #244456;display: block;color:#fff;​font-size:19px !important;">&nbsp;&nbsp;<?php echo $tr->translate("CUSTOMER_INFO");?></div>
											<table width="100%" style="font-size: 12px; font-weight:600;line-height:25px;">
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("COMPANY_NAME");?> </td>
													<td style="text-align: left;white-space: nowrap;">: <?php echo $this->product[0]['customer_name'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("ADDRESS");?> </td>
													<td style="text-align: left;white-space: nowrap;"> :<?php echo $this->product[0]['add_name'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("CONTACT_NAME");?> </td>
													<td style="text-align: left;white-space: nowrap;"> : <?php echo $this->product[0]['contact_name'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("POSITION");?> </td>
													<td style="text-align: left;white-space: nowrap;"> :<?php //echo $this->product[0]['contact_name'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("PHONE");?> </td>
													<td style="text-align: left;white-space: nowrap;"> : <?php echo $this->product[0]['phone'];?></td>
												</tr>
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("EMAIL");?> </td>
													<td style="text-align: left;white-space: nowrap;"> :<?php echo $this->product[0]['email'];?></td>
												</tr>
											</table>
		                				</td>
		                				</td>
		                				<td width="30%"></td>
		                				<td width="35%" valign="top" style="text-align: left;font-size: 15px;">
											<div style="padding-left: 10px;width:100%; background: #244456;display: block;color:#fff;​font-size:19px !important;"><?php echo $tr->translate("DELIVER_INFO");?></div>
											<table width="100%" style="font-size: 12px; font-weight:600; line-height:25px;">
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("DELIVER_NO");?> </td>
													<td>:</td>
													<td style="text-align: right;white-space: nowrap;"><?php echo $this->product[0]['deliver_no'];?></td>
												</tr>
												
												<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("DELIVER_DATE");?> </td>
													<td>:</td>
													<td style="text-align: right;white-space: nowrap;"> <?php echo date("d-M-Y",strtotime($this->product[0]['deli_date']));?></td>
												</tr>
												
												<!--<tr style="line-height:20px;">
													<td style="text-align: left;white-space: nowrap;"><?php echo $tr->translate("BRANCH");?> </td>
													<td>:</td>
													<td style="text-align: right;white-space: nowrap;"> <?php echo $this->product[0]['branch_name'];?></td>
												</tr>-->
											</table>
		                					
		                				</td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
						<tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 40px; font-size:14px !important; padding:1px 0px; white-space: nowrap; ">
		                    <th width="5%">&nbsp;<?php echo $tr->translate("NUM");?></th>
							<th width="15%">&nbsp;<?php echo $tr->translate("ITEM_CODE");?></th>
							<th width="30%"><?php echo $tr->translate("PRODUCT_DISCRIPTION");?></th>
							<!--<th>&nbsp;<?php echo $tr->translate("MODEL");?></th>
							<th width="10%">&nbsp;<?php echo $tr->translate("PRODUCT_FROM");?></th>-->
							<th>&nbsp;<?php echo $tr->translate("QTY");?></th>
							<th width="5%">&nbsp;<?php echo $tr->translate("MEASURE");?></th>
							<th>&nbsp;<?php echo $tr->translate("REMARK");?></th>
							<!--<td width="10%">&nbsp;<?php //echo $tr->translate("OLD_PRICE");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("COST_PRICE");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("BENEFIT_PLUS");?></td>
							<td><?php echo $tr->translate("TOTAL_SALE_PRICE");?></td>-->
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
						$count = count($this->product);
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){ $inx = $index+1;?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <!--<td style="white-space: nowrap;">&nbsp;<?php echo $rs["model_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php //echo $rs["serial_number"];?></td>-->
						   <td style="width:10%;text-align:center;font-weight:800;white-space: nowrap;">&nbsp;<?php echo number_format($rs["qty_order"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["measure"];?></td>
						    <td style="white-space: nowrap;">&nbsp;<?php //echo $rs["serial_number"];?></td>
						   <!--<td style="white-space: nowrap;">&nbsp;<?php echo $rs["price"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["benefit_plus"];?></td>-->
						</tr>
						   <?php 
                    }?>
					
					<?php if($count<10){
						$loop = 10 - $count;
						for($i=1;$i<=$loop;$i++){
					?>
							<tr class='hover' style="border:1px solid #000;">
						   <td align="center">&nbsp;<?php echo $inx+$i?></td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;</td>
						   <td>&nbsp;</td>
						   <td>&nbsp;</td>
						</tr>
					<?php 
							
						}
					}
					?>
						<tr style="border:1px solid #fff; border-bottom:1px solid #000;">
						   <td  style="white-space: nowrap; font-size:13px !important;" colspan="6">&nbsp;សម្គាល់ Remark : 
						         <ul class='pur_info'>
			                		<li style="text-align: left;">អតិថិជនត្រូវពិនិត្យទំនិញទាំងអស់អោយបានត្រឹមត្រូវមុននឹងចុះហត្ថលេខា</li>
									<li style="text-align: left;">យើងខ្ញុំ មិនទទួលខុសត្រូវរាល់ទំនិញខូចខាត ឫបាត់បង់ក្រោយទំនិញខាងលើត្រូវបានប្រគល់រួច។</li>
									<li style="text-align: left;">Please carefully check the above product(s), We are not responible for product(s) demaged or loss.</li>
									<li style="text-align: left;"></li>
			                	</ul>
						   </td> 
						</tr>
						
		                </tbody>
		           </table>
		              <table align="center" width="100%" style="margin-top:15px;">
						   <tbody>
						   <tr style="font-size: 13px;"><br />
						        <td style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'; white-space: nowrap;">អ្នកកាន់ឃ្លាំង  / Stock Controller</td>
						        <td></td>
						        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';white-space: nowrap;">អ្នកដឹក  / Delivery Man</td>
						        <td></td>
						        <td style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;">អតិថិជន  /​ Customer</td>
						   </tr>
						   <tr style="font-size: 13px; height: 105px;">
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer OS Muol Light';white-space: nowrap;border-bottom:1px solid #000;"></td>
						   </tr>
						   
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=document.getElementById('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    //hideDialog();
}

</script>
