<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("Invoice Report");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("Invoice Report");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;បោះពុម្ភ/Print
										</a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0" >
		            	<tbody><tr>
		                	<td width="40%" valign="top" style="text-align:left; font-size:18px; font-family:'Khmer MEF2'">សូរ៉ា ហាងលក់សម្ភារអគ្គិសនី</td>
		                	<td width="20%" valign="top">
		                		
		                	</td>
		                    <td width="40%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 11px;" valign="top" width="35%;">
		                				<div style="width:100%; background: #244456;display: block;color:#fff;">&nbsp;&nbsp;Customer Information</div>
		                				   <ul class='pur_info'>
			                					<li style="text-align: left;"><strong>Company Name : </strong><?php echo $this->product[0]['customer_name'];?></li>
			                					<li style="text-align: left;"><strong>Contact Person : </strong><?php echo $this->product[0]['contact_name'];?></li>
			                					<li style="text-align: left;"><strong>Contact Number : </strong><?php echo $this->product[0]['phone'];?></li>
			                					<li style="text-align: left;"><strong>Email : </strong><?php echo $this->product[0]['email'];?></li>
			                					<li style="text-align: left;"><strong>Address: </strong><?php echo $this->product[0]['add_name'];?></li>
		                					</ul>
		                				</td>
		                				<td width="30%"></td>
		                				<td width="35%" style="text-align: left;font-size: 11px;">
		                					<div style="width:100%; background: #244456;display: block;color:#fff;">&nbsp;&nbsp;Official Invoice</div>
		                					<ul class='pur_info'>
			                					<li style="text-align: left;"><strong>Location : </strong><?php echo $this->product[0]['branch_name'];?></li>
			                					<li style="text-align: left;"><strong>Invoice No. : </strong><?php echo $this->product[0]['invoice_no'];?></li>
		                					    <li style="text-align: left;"><strong>Date : </strong><?php echo date("d/m/Y",strtotime($this->product[0]['invoice_date']));?></li>
		                						<li style="text-align: left;"><strong>Sale Person : </strong><?php echo $this->product[0]['staff_name'];?></li>
		                					    <li style="text-align: left;"><strong>Bill Issuer : </strong><?php echo $this->product[0]['biller'];?></li>
		                					    
			                			    </ul>
		                				</td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel"><br />
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:10px;" width="100%" cellspacing="0">
		                 <tbody>
						<tr align="center" style="font-weight:bold; line-height: 20px;  padding:1px 0px; white-space: nowrap;border:1px solid #fff;border-bottom: 1px solid #000 !important; ">
		                    <td colspan="7" align="center" style="font-size: 13px;">ទំនិញដែលបានទិញហើយក្រុមហ៊ុនយើងខ្ញុំ មិនទទួលដូរយកវិញទេ ។សូមអរគុណ
		                    <br>Goods Sold Can Not Be Returned, Thank you !</td>
		                </tr>
						<tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							<td><?php echo $tr->translate("PRODUCT_DISCRIPTION");?></td>
							<td>&nbsp;<?php echo $tr->translate("QTY");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("UNIT_PRICE_CAP");?></td>
							<td>&nbsp;<?php echo $tr->translate("AMOUNT");?></td>
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->product))foreach ($this->product AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["qty_order"];?></td>
						   <td>&nbsp;<?php echo $rs["curr_name"]."&nbsp;";echo number_format($rs["price"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo number_format($rs["dsub_total"],2);?>​ <?php //echo number_format(($rs["qty_detail"]),0).$rs['unit_label'];?></td>
						   
						</tr>
						   <?php  }?>
					<tr>
						<td colspan="3" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td  style="border-left:1px solid #000;">&nbsp;&nbsp;Total</td>
						<td>&nbsp;<?php echo number_format($this->product[0]['sub_total'],2);?></td>
					</tr>
					<tr>
						<td colspan="3" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td  style="border-left:1px solid #000;">&nbsp;&nbsp;Discount</td>
						<td>&nbsp;<?php echo number_format($this->product[0]['vdiscount'],2);?></td>
					</tr>
					
					<tr>
						<td colspan="3" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td  style="border-left:1px solid #000;">&nbsp;&nbsp;Deposit</td>
						<td>&nbsp;<?php echo number_format($this->product[0]['paid_amount'],2);?></td>
					</tr>
					<tr>
						<td colspan="3" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #000;"></td>
						<td  style="border-left:1px solid #000;border-bottom:1px solid #000;">&nbsp;&nbsp;Balance</td>
						<td style="border-left:1px solid #000;border-bottom:1px solid #000;">&nbsp;<?php echo number_format($this->product[0]['balance'],2);?></td>
					</tr>
						<tr  style="border:1px solid #fff;border-bottom:1px solid #000;" height="20px">
							<td colspan="7">&nbsp;</td>
						</tr>
						<tr  style="border:1px solid #000;">
						   <td style="white-space: nowrap;" colspan="5">
								 <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:10px; margin:0 auto;" width="98%" cellspacing="0">
									<tr style="text-align:left;">
										<td colspan="7" style="border:1px solid #fff; ">សម្គាល់</td>
									</tr>
									<tr style="text-align:left;">
										<td colspan="7" style="border:1px solid #fff; border-bottom:1px solid #000; ">ទឹកប្រាក់នៅខ្វះពីលើកមុន</td>
									</tr>
									<tr style="text-align:center;">
										<td>ល.រ</td>
										<td>ថ្ងៃ/ខែ/ឆ្នាំ</td>
										<td>វិក័យបត្រ</td>
										<td>ចំនួនទឹកប្រាក់</td>
										<td>បញ្ចុះតម្លៃ</td>
										<td>ទឹកប្រាក់បានបង់</td>
										<td>ទឹកប្រាក់នៅខ្វះ</td>
									</tr>
									<?php $balance = 0;if(!empty($this->rsinvoice)) foreach($this->rsinvoice as $key =>$rs){?>
									<tr style="text-align:center;">
										<td><?php echo $key+1;?></td>
										<td><?php echo date("d/m/Y",strtotime($rs["invoice_date"]));?></td>
										<td><?php echo $rs["invoice_no"];?></td>
										<td><?php echo $rs["sub_total"];?></td>
										<td><?php echo $rs["discount"];?></td>
										<td><?php echo $rs["paid_amount"];//ត្រូវយកប្រាក់ដែលបានបង់សរុប?></td>
										<td><?php echo $rs["balance"];
										$balance =$balance + $rs["balance"];
										?></td>
									</tr>
									<?php } ?>
									<tr ">
									    <td colspan="6" style="font-size:14px;border-bottom:1px solid #fff;border-left:1px solid #fff;text-align:right; ">ប្រាក់នៅខ្វះរួមសរុប&nbsp;</td>
										<td style="border-left:1px solid #000;font-size:14px;">$&nbsp;<?php echo number_format($balance,2);?></td>
									</tr>									
								</table><br />
						   </td> 
						</tr>
						<tr>
							<td colspan="7" style="border:1px solid #fff;border-top:1px solid #000;border-right:1px solid #fff;">
							<strong  style="font-size: 13px;"><u>ខសន្យា និងលក្ខណ៏ទូទៅ / General Term & Conditions</u></strong>
								<style>
									ul.termcodition li{ line-height: 20px;list-style-type: none; font-size: 12px;}
								</style>
								<ul class="termcodition">
								<?php if(!empty($this->rscondition))foreach ($this->rscondition as $key =>$rst){ ?>
									<li style="text-align: left;"><?php echo $key+1;echo "-".$rst['con_khmer'];?></li>
									<li style="text-align: left;"><?php echo $rst['con_english'];?></li>
								<?php }?>
								</ul>
							</td>
					</tr>
		                </tbody>
		           </table>
				    
		              <table align="center" width="100%">
						   <tbody>
						   <tr style="font-size: 11px;">
						        <td style="width:20%;text-align:center;  font-family:'Khmer MEF2'; white-space: nowrap;">អ្នកកាន់ឃ្លាំង  / Stock Controller</td>
						        <td></td>
						        <td style="width:20%;text-align:center; font-family:'Khmer MEF2';white-space: nowrap;">អ្នកដឹក  / Delivery Man</td>
						        <td></td>
						        <td style="width:20%;text-align:center;font-family:'Khmer MEF2';white-space: nowrap;">អតិថិជន  /​ Customer</td>
						   </tr>
						   <tr style="font-size: 11px; height: 75px;">
						        <td valign="bottom" style="width:20%;text-align:center;  font-family:'Khmer MEF2'; white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center; font-family:'Khmer MEF2';white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
						        <td></td>
						        <td valign="bottom" style="width:20%;text-align:center;font-family:'Khmer MEF2';white-space: nowrap;">ឈ្មោះ  /Name--------------------------</td>
						   </tr>
						   <tr style="font-size: 11px;">
						        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
						        <td></td>
						        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
						        <td></td>
						        <td style="width:20%;text-align:center;white-space: nowrap;">ថ្ងៃ  /Date:----------------------------------</td>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	var printContents = document.getElementById('divPrint').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
}

</script>
